import { env } from "../config/env.js";

const baseUrl = () => env.PAYPAL_ENVIRONMENT === "live" ? "https://api-m.paypal.com" : "https://api-m.sandbox.paypal.com";
function configured() { if (!env.PAYPAL_CLIENT_ID || !env.PAYPAL_CLIENT_SECRET) throw new Error("PayPal is not configured."); return { clientId: env.PAYPAL_CLIENT_ID, clientSecret: env.PAYPAL_CLIENT_SECRET }; }
async function accessToken() { const { clientId, clientSecret } = configured(); const authorization = Buffer.from(`${clientId}:${clientSecret}`).toString("base64"); const response = await fetch(`${baseUrl()}/v1/oauth2/token`, { method: "POST", headers: { Authorization: `Basic ${authorization}`, "Content-Type": "application/x-www-form-urlencoded" }, body: "grant_type=client_credentials" }); if (!response.ok) throw new Error("PayPal authentication failed."); return (await response.json() as { access_token: string }).access_token; }
export async function createOrder(referenceId: string) { const token = await accessToken(); const amountCents = env.PRO_PASS_PRICE_CENTS ?? env.PRO_MONTHLY_PRICE_CENTS; const response = await fetch(`${baseUrl()}/v2/checkout/orders`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "PayPal-Request-Id": referenceId }, body: JSON.stringify({ intent: "CAPTURE", purchase_units: [{ reference_id: referenceId, description: "MidiFlow Pro Pass — 30 days", amount: { currency_code: env.PRO_CURRENCY, value: (amountCents / 100).toFixed(2) } }], application_context: { shipping_preference: "NO_SHIPPING", user_action: "PAY_NOW" } }) }); if (!response.ok) throw new Error("PayPal order creation failed."); return response.json() as Promise<{ id: string; status: string }>; }
export async function captureOrder(orderId: string) { const token = await accessToken(); const response = await fetch(`${baseUrl()}/v2/checkout/orders/${orderId}/capture`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "PayPal-Request-Id": `capture-${orderId}` } }); if (!response.ok) throw new Error("PayPal capture failed."); return response.json() as Promise<{ id: string; status: string; purchase_units: Array<{ payments?: { captures?: Array<{ id: string; status: string; amount: { value: string; currency_code: string }; create_time: string }> } }> }>;
}
export async function verifyWebhook(headers: Record<string, string | undefined>, event: unknown) { if (!env.PAYPAL_WEBHOOK_ID) return false; const token = await accessToken(); const response = await fetch(`${baseUrl()}/v1/notifications/verify-webhook-signature`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ auth_algo: headers["paypal-auth-algo"], cert_url: headers["paypal-cert-url"], transmission_id: headers["paypal-transmission-id"], transmission_sig: headers["paypal-transmission-sig"], transmission_time: headers["paypal-transmission-time"], webhook_id: env.PAYPAL_WEBHOOK_ID, webhook_event: event }) }); if (!response.ok) return false; const data = await response.json() as { verification_status?: string }; return data.verification_status === "SUCCESS"; }
export async function sendPayout(input: { senderBatchId: string; receiver: string; amountValue: string; currency: string; note: string }) { const token = await accessToken(); const response = await fetch(`${baseUrl()}/v1/payments/payouts`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ sender_batch_header: { sender_batch_id: input.senderBatchId, email_subject: "You have a MidiFlow referral payout", email_message: input.note }, items: [{ recipient_type: "EMAIL", amount: { value: input.amountValue, currency: input.currency }, receiver: input.receiver, note: input.note, sender_item_id: input.senderBatchId }] }) }); if (!response.ok) throw new Error("PayPal payout failed."); const data = await response.json() as { batch_header?: { payout_batch_id?: string; batch_status?: string }; items?: Array<{ payout_item_id?: string; transaction_status?: string }> }; return { payoutBatchId: data.batch_header?.payout_batch_id ?? null, payoutItemId: data.items?.[0]?.payout_item_id ?? null, batchStatus: data.batch_header?.batch_status ?? data.items?.[0]?.transaction_status ?? null }; }
