import type { ArtistProfile } from "./types.js";

export const ARTIST_ORIGINALITY_NOTICE = "Create an original composition inspired by the following musical characteristics. Do not reproduce, imitate, or closely resemble any existing song, melody, hook, lyric, or copyrighted musical work.";

export const DIRECT_COPY_PATTERNS = [
  /\bcopy (this|the) exact (song|melody|hook|beat|composition)\b/i,
  /\bremake (the )?(original|exact) (song|melody|hook|notes)\b/i,
  /\buse the same notes as\b/i,
  /\bsame melody as\b/i,
  /\brecreate (this|that|the) exact (song|melody|hook)\b/i,
  /\bidentical to\b/i,
  /\bclone\b.*\b(song|melody|hook|arrangement)\b/i,
];

export const ARTIST_REFERENCE_PATTERNS = [
  /\btype\b/i,
  /\bstyle\b/i,
  /\bvibe\b/i,
  /\binspired by\b/i,
  /\blike\b/i,
  /\bexact\b/i,
];

export const SUPPORTED_KNOWLEDGE_GENRES = [
  "Trap",
  "Drill",
  "Hip Hop",
  "Boom Bap",
  "LoFi",
  "House",
  "EDM",
  "Tech House",
  "Techno",
  "Future Bass",
  "Dubstep",
  "Dancehall",
  "Afrobeats",
  "Reggae",
  "R&B",
  "Soul",
  "Pop",
  "Rock",
  "Jazz",
  "Blues",
  "Country",
  "Classical",
  "Orchestral",
  "Synthwave",
  "Phonk",
  "Cinematic",
  "Ambient",
  "Latin",
  "Gospel",
] as const;

export const VIBE_MOOD_MAP: Record<string, string[]> = {
  bouncy: ["Energetic", "Confident"],
  dark: ["Dark", "Mysterious"],
  emotional: ["Emotional", "Melancholy"],
  aggressive: ["Aggressive", "Dark"],
  dreamy: ["Dreamy", "Mysterious"],
  epic: ["Epic", "Inspirational"],
  relaxed: ["Relaxed", "Hopeful"],
  sad: ["Sad", "Melancholy"],
  happy: ["Happy", "Hopeful"],
  spacey: ["Dreamy", "Mysterious"],
  cinematic: ["Epic", "Mysterious"],
  melancholic: ["Melancholy", "Emotional"],
};

export const VIBE_GROOVE_MAP: Record<string, string> = {
  bouncy: "Bouncy",
  swing: "Swing-led",
  groovy: "Groove-forward",
  skippy: "Skippy",
  spacey: "Floating",
  cinematic: "Evolving",
};

export const VIBE_ENERGY_MAP: Record<string, "Low" | "Medium" | "Medium High" | "High" | "Extreme"> = {
  bouncy: "High",
  aggressive: "High",
  dark: "Medium High",
  dreamy: "Medium",
  relaxed: "Low",
  sad: "Low",
  happy: "Medium",
  epic: "High",
  spacey: "Medium",
  cinematic: "Medium High",
  emotional: "Medium",
  melancholic: "Low",
};

export const INSTRUMENT_HINTS = [
  "Bright Piano",
  "Piano",
  "Bell",
  "808",
  "Pad",
  "Choir",
  "Lead",
  "Guitar",
  "Bass",
  "Strings",
  "Percussion",
  "Synth",
  "Keys",
];

export const ARTIST_PROFILES: ArtistProfile[] = [
  {
    artistName: "Skippa",
    aliases: ["skippa", "skippa type"],
    primaryGenre: "Jamaican Trap Dancehall",
    secondaryGenre: "Dancehall Trap",
    knowledgeGenres: ["Dancehall", "Trap", "Afrobeats"],
    tempoMin: 95,
    tempoMax: 110,
    defaultTempo: 102,
    energyLevel: "High",
    moodTags: ["Aggressive", "Energetic", "Confident"],
    instrumentTags: ["Bright Piano", "Bell", "808", "Percussion"],
    grooveStyle: "Bouncy",
    melodyStyle: "Sparse, syncopated, piano-led",
    rhythmStyle: "Skippy dancehall pockets with trap hi-hat support",
    productionStyle: "Bright melodic top lines over punchy low-end",
    chordStyle: "Minimal minor loops with fast turnaround movement",
    description: "Generalized high-energy Jamaican trap dancehall profile built around bouncy piano motifs, syncopated bells, and urgent rhythmic motion.",
    characteristics: [
      { type: "groove", value: "Bouncy pocket with medium swing", priority: 10 },
      { type: "melody", value: "Sparse piano phrases with syncopated accents", priority: 9 },
      { type: "rhythm", value: "Dancehall bounce reinforced by trap hats", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Vybz Kartel",
    aliases: ["vybz kartel", "kartel"],
    primaryGenre: "Dancehall",
    secondaryGenre: "Modern Jamaican Club",
    knowledgeGenres: ["Dancehall", "Reggae", "Afrobeats"],
    tempoMin: 96,
    tempoMax: 112,
    defaultTempo: 104,
    energyLevel: "High",
    moodTags: ["Confident", "Energetic", "Aggressive"],
    instrumentTags: ["Keys", "Bell", "Bass", "Percussion"],
    grooveStyle: "Bouncy",
    melodyStyle: "Hook-first, chant-friendly, rhythmic",
    rhythmStyle: "Dancehall dembow with clipped syncopation",
    productionStyle: "Dry drums, bold bass, bright melodic punctuation",
    chordStyle: "Direct loops with repetitive hook support",
    description: "Generalized dancehall profile emphasizing rhythmic confidence, clipped melodies, and club-ready low-end.",
    characteristics: [
      { type: "groove", value: "Forward dembow pulse", priority: 10 },
      { type: "melody", value: "Rhythmic call-and-response phrasing", priority: 9 },
      { type: "production", value: "Dry percussion and assertive bass", priority: 7 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Popcaan",
    aliases: ["popcaan", "unruly"],
    primaryGenre: "Dancehall Afrobeats Crossover",
    secondaryGenre: "Melodic Caribbean Pop",
    knowledgeGenres: ["Dancehall", "Afrobeats", "Pop"],
    tempoMin: 92,
    tempoMax: 108,
    defaultTempo: 100,
    energyLevel: "Medium High",
    moodTags: ["Happy", "Dreamy", "Confident"],
    instrumentTags: ["Guitar", "Bell", "Keys", "Percussion"],
    grooveStyle: "Rolling",
    melodyStyle: "Melodic, airy, lightly syncopated",
    rhythmStyle: "Laid-back dancehall with crossover bounce",
    productionStyle: "Warm plucks, guitars, and soft atmospheric support",
    chordStyle: "Major/minor crossover loops with open space",
    description: "Generalized melodic Caribbean crossover profile with airy hooks, rolling percussion, and warm topline motion.",
    characteristics: [
      { type: "groove", value: "Rolling dancehall bounce", priority: 10 },
      { type: "melody", value: "Airy top lines with memorable contour", priority: 9 },
      { type: "production", value: "Warm guitars and open pluck layers", priority: 7 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Burna Boy",
    aliases: ["burna boy", "burna"],
    primaryGenre: "Afrofusion",
    secondaryGenre: "Afrobeats",
    knowledgeGenres: ["Afrobeats", "Dancehall", "Pop"],
    tempoMin: 96,
    tempoMax: 116,
    defaultTempo: 108,
    energyLevel: "Medium High",
    moodTags: ["Hopeful", "Energetic", "Relaxed"],
    instrumentTags: ["Guitar", "Keys", "Bass", "Percussion"],
    grooveStyle: "Rolling",
    melodyStyle: "Conversational, spacious, groove-led",
    rhythmStyle: "Percussion-first afro pocket with live-feel movement",
    productionStyle: "Warm guitars, roomy drums, organic low-end",
    chordStyle: "Accessible progressions with rhythmic harmonic repetition",
    description: "Generalized afrofusion profile focused on groove-first arrangements, warm guitars, and organic percussion lift.",
    characteristics: [
      { type: "groove", value: "Percussion-led rolling pocket", priority: 10 },
      { type: "rhythm", value: "Live-feel afro groove with push-pull motion", priority: 9 },
      { type: "production", value: "Organic layers and warm bass support", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Drake",
    aliases: ["drake", "drizzy"],
    primaryGenre: "Melodic Rap and R&B",
    secondaryGenre: "Contemporary Pop Rap",
    knowledgeGenres: ["R&B", "Hip Hop", "Pop"],
    tempoMin: 70,
    tempoMax: 110,
    defaultTempo: 88,
    energyLevel: "Medium",
    moodTags: ["Emotional", "Confident", "Melancholy"],
    instrumentTags: ["Keys", "Pad", "Bass", "Bell"],
    grooveStyle: "Measured",
    melodyStyle: "Conversational, moody, motif-based",
    rhythmStyle: "Minimal rap pocket with subtle bounce",
    productionStyle: "Clean atmospheric textures over focused drums",
    chordStyle: "Minor-leaning loops with emotional color tones",
    description: "Generalized melodic rap and R&B profile with moody keys, atmospheric space, and controlled rhythmic confidence.",
    characteristics: [
      { type: "groove", value: "Subtle bounce with room for phrasing", priority: 10 },
      { type: "melody", value: "Motif-led melodic phrasing", priority: 8 },
      { type: "production", value: "Atmospheric and clean with emotional restraint", priority: 7 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Future",
    aliases: ["future", "pluto"],
    primaryGenre: "Melodic Trap",
    secondaryGenre: "Dark Rap",
    knowledgeGenres: ["Trap", "Hip Hop", "Phonk"],
    tempoMin: 130,
    tempoMax: 150,
    defaultTempo: 144,
    energyLevel: "Medium High",
    moodTags: ["Dark", "Emotional", "Aggressive"],
    instrumentTags: ["Pad", "Bell", "808", "Keys"],
    grooveStyle: "Head-nod",
    melodyStyle: "Sparse, moody, repetitive",
    rhythmStyle: "Half-time trap with rolling hats",
    productionStyle: "Dark textures, heavy sub, minimal harmonic clutter",
    chordStyle: "Simple minor loops with suspended tension",
    description: "Generalized melodic trap profile with heavy low-end, dark pads, and repetitive emotional motifs.",
    characteristics: [
      { type: "groove", value: "Heavy half-time trap pocket", priority: 10 },
      { type: "melody", value: "Moody repetition with simple contour", priority: 9 },
      { type: "production", value: "Dark pads and sub-led space", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Metro Boomin",
    aliases: ["metro boomin", "metro"],
    primaryGenre: "Cinematic Trap",
    secondaryGenre: "Dark Trap",
    knowledgeGenres: ["Trap", "Cinematic", "Phonk"],
    tempoMin: 140,
    tempoMax: 148,
    defaultTempo: 144,
    energyLevel: "Medium High",
    moodTags: ["Dark", "Mysterious", "Aggressive"],
    instrumentTags: ["Bell", "Pad", "808", "Choir"],
    grooveStyle: "Heavy",
    melodyStyle: "Sparse, atmospheric, motif-driven",
    rhythmStyle: "Hard trap drums with fast hats and dramatic pauses",
    productionStyle: "Dark bells, wide pads, dramatic transitions, deep 808s",
    chordStyle: "Minimal minor harmony with cinematic tension",
    description: "Generalized cinematic trap profile driven by dark bell motifs, wide pads, dramatic spacing, and heavyweight low-end.",
    characteristics: [
      { type: "groove", value: "Heavy trap bounce with pause-based tension", priority: 10 },
      { type: "melody", value: "Atmospheric motifs anchored by bells", priority: 9 },
      { type: "production", value: "Wide dark atmosphere and impact transitions", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Pop Smoke",
    aliases: ["pop smoke", "woo"],
    primaryGenre: "Brooklyn Drill",
    secondaryGenre: "Dark Drill",
    knowledgeGenres: ["Drill", "Hip Hop", "Trap"],
    tempoMin: 140,
    tempoMax: 145,
    defaultTempo: 143,
    energyLevel: "High",
    moodTags: ["Aggressive", "Dark", "Confident"],
    instrumentTags: ["Piano", "Strings", "808", "Choir"],
    grooveStyle: "Driving",
    melodyStyle: "Simple, menacing, chant-friendly",
    rhythmStyle: "Drill bounce with sliding bass and syncopated snare answers",
    productionStyle: "Cold pianos, hard bass, stark space, dramatic accents",
    chordStyle: "Tense minor loops with narrow harmonic range",
    description: "Generalized Brooklyn drill profile emphasizing cold piano motifs, sliding low-end, and aggressive rhythmic drive.",
    characteristics: [
      { type: "groove", value: "Driving drill rhythm with stern pocket", priority: 10 },
      { type: "melody", value: "Menacing piano fragments", priority: 9 },
      { type: "rhythm", value: "Sliding sub bass and syncopated response hits", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Lil Baby",
    aliases: ["lil baby", "baby"],
    primaryGenre: "Modern Trap Rap",
    secondaryGenre: "Melodic Street Rap",
    knowledgeGenres: ["Trap", "Hip Hop", "R&B"],
    tempoMin: 132,
    tempoMax: 150,
    defaultTempo: 142,
    energyLevel: "Medium High",
    moodTags: ["Confident", "Energetic", "Emotional"],
    instrumentTags: ["Keys", "Bell", "808", "Pad"],
    grooveStyle: "Forward",
    melodyStyle: "Compact, melodic, phrase-driven",
    rhythmStyle: "Tight trap groove with vocal-pocket spacing",
    productionStyle: "Melodic loops with firm low-end and clean percussion framing",
    chordStyle: "Minor loops with direct melodic support",
    description: "Generalized modern trap rap profile blending melodic loop writing with firm low-end and direct rhythmic energy.",
    characteristics: [
      { type: "groove", value: "Forward trap momentum", priority: 10 },
      { type: "melody", value: "Compact melodic loops supporting phrasing", priority: 8 },
      { type: "production", value: "Clean percussion around firm low-end", priority: 7 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Travis Scott",
    aliases: ["travis scott", "travis", "la flame"],
    primaryGenre: "Psychedelic Trap",
    secondaryGenre: "Atmospheric Hip Hop",
    knowledgeGenres: ["Trap", "Cinematic", "Synthwave"],
    tempoMin: 128,
    tempoMax: 150,
    defaultTempo: 138,
    energyLevel: "Medium High",
    moodTags: ["Dark", "Dreamy", "Epic"],
    instrumentTags: ["Pad", "Lead", "Bell", "808"],
    grooveStyle: "Swaying",
    melodyStyle: "Atmospheric, hypnotic, effects-friendly",
    rhythmStyle: "Trap drums with wide pockets and swelling transitions",
    productionStyle: "Large reverbs, distorted ambience, layered synth space",
    chordStyle: "Minimal moody harmony with suspended color",
    description: "Generalized atmospheric trap profile with hypnotic motifs, wide synth space, and dramatic production movement.",
    characteristics: [
      { type: "groove", value: "Wide swaying trap pocket", priority: 10 },
      { type: "production", value: "Large-scale ambience and transitions", priority: 9 },
      { type: "melody", value: "Hypnotic motifs with atmospheric spacing", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "Rod Wave",
    aliases: ["rod wave", "rod"],
    primaryGenre: "Soul Trap",
    secondaryGenre: "Melodic Piano Rap",
    knowledgeGenres: ["R&B", "Soul", "Trap"],
    tempoMin: 68,
    tempoMax: 88,
    defaultTempo: 76,
    energyLevel: "Medium",
    moodTags: ["Sad", "Emotional", "Hopeful"],
    instrumentTags: ["Piano", "Strings", "Choir", "808"],
    grooveStyle: "Slow-swaying",
    melodyStyle: "Emotive, piano-led, singable",
    rhythmStyle: "Slow trap pulse with vocal room and dramatic swells",
    productionStyle: "Warm piano, soft strings, supportive sub bass",
    chordStyle: "Emotional minor progressions with gospel color",
    description: "Generalized soul-trap profile with emotional piano writing, supportive strings, and slow-moving dramatic momentum.",
    characteristics: [
      { type: "melody", value: "Emotive piano-led lines", priority: 10 },
      { type: "chord", value: "Soulful minor progressions with lift", priority: 9 },
      { type: "production", value: "Warm piano and orchestral support", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
  {
    artistName: "The Weeknd",
    aliases: ["the weeknd", "weeknd", "abel"],
    primaryGenre: "Dark Synth R&B",
    secondaryGenre: "Alternative Pop",
    knowledgeGenres: ["R&B", "Synthwave", "Pop"],
    tempoMin: 80,
    tempoMax: 122,
    defaultTempo: 100,
    energyLevel: "Medium",
    moodTags: ["Dark", "Dreamy", "Romantic"],
    instrumentTags: ["Synth", "Pad", "Bass", "Keys"],
    grooveStyle: "Steady",
    melodyStyle: "Smooth, nocturnal, hook-forward",
    rhythmStyle: "Tight pop pulse with dark R&B atmosphere",
    productionStyle: "Retro synth layers, moody bass, polished atmosphere",
    chordStyle: "Minor pop progressions with lush extensions",
    description: "Generalized dark synth-R&B profile centered on nocturnal synth textures, smooth hook writing, and polished pop structure.",
    characteristics: [
      { type: "production", value: "Retro synth polish with dark atmosphere", priority: 10 },
      { type: "melody", value: "Hook-forward nocturnal phrasing", priority: 9 },
      { type: "chord", value: "Lush minor pop harmony", priority: 8 },
      { type: "originality", value: "High originality requirement", priority: 1 },
    ],
  },
];