import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import * as billing from "../controllers/billing.controller.js";
export const billingRouter = Router();
billingRouter.get("/membership", requireAuth, billing.membership);
billingRouter.get("/membership/history", requireAuth, billing.membershipHistory);
billingRouter.post("/membership/upgrade", requireAuth, billing.upgradeMembership);
billingRouter.post("/membership/renew", requireAuth, billing.renewMembership);
billingRouter.get("/trial/status", requireAuth, billing.trialStatus);
billingRouter.post("/trial/start", requireAuth, billing.startTrial);
billingRouter.get("/payments", requireAuth, billing.payments);
billingRouter.get("/billing", requireAuth, billing.payments);
billingRouter.post("/paypal/create-order", requireAuth, billing.createPaypalOrder);
billingRouter.post("/paypal/capture-order/:orderId", requireAuth, billing.capturePaypalOrder);
billingRouter.post("/renew", requireAuth, billing.createPaypalOrder);
billingRouter.post("/paypal/webhook", billing.webhook);
