import type { Request, Response } from "express";
import { randomUUID } from "node:crypto";
import { requireSupabase } from "../config/supabase.js";
import type { AuthRequest } from "../middleware/auth.js";
import { captureOrder, createOrder, verifyWebhook } from "../paypal/paypal.service.js";
import { monthlyCreditSummary } from "../services/credit.service.js";
import { cancelMembershipAtPeriodEnd, convertUserToPro, endTrial, extendTrial, grantProAccess, membershipFor, membershipHistoryFor, membershipUsers, paymentsFor, planPrices, startTrialMembership, trialAnalytics, trialStatusFor, type MembershipPlan } from "../services/membership.service.js";
import { referralDiscountFor } from "../services/referral.service.js";
import { z } from "zod";

export async function membership(request: AuthRequest, response: Response) { try { const [membership, credits] = await Promise.all([membershipFor(request.user!.id), monthlyCreditSummary(request.user!.id)]); response.json({ data: { ...membership, prices: planPrices(), price: planPrices()[membership.plan], credits } }); } catch { response.status(500).json({ error: "Unable to retrieve membership" }); } }
export async function trialStatus(request: AuthRequest, response: Response) { try { response.json({ data: await trialStatusFor(request.user!.id) }); } catch { response.status(500).json({ error: "Unable to retrieve trial status" }); } }
export async function startTrial(request: AuthRequest, response: Response) { try { response.status(201).json({ data: await startTrialMembership(request.user!.id) }); } catch (error) { const status = (error as { statusCode?: number }).statusCode ?? 500; response.status(status).json({ error: error instanceof Error ? error.message : "Unable to start trial" }); } }
export async function payments(request: AuthRequest, response: Response) { try { response.json({ data: await paymentsFor(request.user!.id) }); } catch { response.status(500).json({ error: "Unable to retrieve payments" }); } }
export async function cancelMembership(request: AuthRequest, response: Response) { try { response.json({ data: await cancelMembershipAtPeriodEnd(request.user!.id) }); } catch (error) { const status = (error as { statusCode?: number }).statusCode ?? 500; response.status(status).json({ error: error instanceof Error ? error.message : "Unable to schedule cancellation" }); } }
export async function membershipHistory(request: AuthRequest, response: Response) { try { response.json({ data: await membershipHistoryFor(request.user!.id) }); } catch { response.status(500).json({ error: "Unable to retrieve membership history" }); } }
async function createPassOrder(request: AuthRequest, response: Response, kind: "pro_pass" | "renewal") { try { const parsed = z.object({ plan: z.enum(["go", "plus"]).default("plus") }).safeParse(request.body ?? {}); if (!parsed.success) return response.status(422).json({ error: "Invalid plan" }); const plan = parsed.data.plan as MembershipPlan; const reference = `${request.user!.id}:${randomUUID()}`; const price = planPrices()[plan]; const discount = await referralDiscountFor(request.user!.id, plan, price.amountCents); const amountCents = discount?.amountCents ?? price.amountCents; const order = await createOrder(reference, plan, amountCents); const { error } = await requireSupabase().from("payments").insert({ user_id: request.user!.id, paypal_order_id: order.id, amount_cents: amountCents, original_amount_cents: price.amountCents, discount_percent: discount?.percent ?? 0, discount_amount_cents: discount?.discountAmountCents ?? 0, currency: price.currency, membership_days: price.days, payment_kind: kind, plan, status: "created" }); if (error) throw error; response.status(201).json({ data: { orderId: order.id, kind, plan, discountPercent: discount?.percent ?? 0, amountCents } }); } catch (error) { response.status(502).json({ error: error instanceof Error ? error.message : "Unable to create PayPal order" }); } }
export async function upgradeMembership(request: AuthRequest, response: Response) { return createPassOrder(request, response, "pro_pass"); }
export async function renewMembership(request: AuthRequest, response: Response) { return createPassOrder(request, response, "renewal"); }
export async function createPaypalOrder(request: AuthRequest, response: Response) { return createPassOrder(request, response, "pro_pass"); }
export async function capturePaypalOrder(request: AuthRequest, response: Response) { const orderId = String(request.params.orderId); try { const db = requireSupabase(); const { data: payment, error: lookupError } = await db.from("payments").select("*").eq("paypal_order_id", orderId).eq("user_id", request.user!.id).single(); if (lookupError || !payment) return response.status(404).json({ error: "Payment order not found" }); if (payment.status === "completed") return response.status(409).json({ error: "Payment has already been captured" }); const capture = await captureOrder(orderId); const captureData = capture.purchase_units[0]?.payments?.captures?.[0]; if (capture.status !== "COMPLETED" || !captureData || captureData.status !== "COMPLETED") return response.status(422).json({ error: "PayPal did not complete the capture" }); const expected = (payment.amount_cents / 100).toFixed(2); if (captureData.amount.currency_code !== payment.currency || captureData.amount.value !== expected) return response.status(422).json({ error: "Captured amount does not match the order" }); const { data: claimedPayment, error: updateError } = await db.from("payments").update({ status: "completed", paypal_capture_id: captureData.id, last_verified_at: new Date().toISOString() }).eq("id", payment.id).eq("status", "created").select().maybeSingle(); if (updateError) throw updateError; if (!claimedPayment) return response.status(409).json({ error: "Payment capture is already being processed" }); const currentMembership = await membershipFor(request.user!.id); const access = await grantProAccess(request.user!.id, payment.id, currentMembership.type === "pro" ? "renewal_extension" : "purchase"); const invoice = `MF-${new Date().getUTCFullYear()}-${payment.id.slice(0, 8).toUpperCase()}`; await db.from("payments").update({ access_starts_at: access.startsAt, access_expires_at: access.expiresAt }).eq("id", payment.id); await db.from("billing_history").insert({ user_id: request.user!.id, payment_id: payment.id, invoice_number: invoice }); await db.from("payment_events").insert({ payment_id: payment.id, user_id: request.user!.id, event_type: "PAYMENT.CAPTURE.COMPLETED", paypal_event_id: captureData.id, payload: capture }); await db.from("payment_logs").insert({ payment_id: payment.id, user_id: request.user!.id, level: "info", message: "PayPal payment captured and membership extended", metadata: { expiresAt: access.expiresAt } }); response.json({ data: { membership: await membershipFor(request.user!.id), access, invoiceNumber: invoice } }); } catch (error) { response.status(502).json({ error: error instanceof Error ? error.message : "Unable to capture payment" }); } }
export async function webhook(request: Request, response: Response) { const event = request.body as { id?: string; event_type?: string; resource?: { id?: string; supplementary_data?: { related_ids?: { order_id?: string } } } }; try { if (!event.id || !event.event_type) return response.status(400).json({ error: "Invalid PayPal webhook payload" }); const headers: Record<string, string | undefined> = Object.fromEntries(Object.entries(request.headers).map(([key, value]) => [key.toLowerCase(), Array.isArray(value) ? value[0] : value])); const verified = await verifyWebhook(headers, event); const db = requireSupabase(); const { error: insertError } = await db.from("paypal_webhooks").insert({ paypal_event_id: event.id, event_type: event.event_type, verified, payload: event, processed_at: new Date().toISOString() }); if (insertError?.code === "23505") return response.status(200).json({ received: true, duplicate: true }); if (insertError) throw insertError; if (!verified) return response.status(400).json({ error: "Invalid PayPal webhook signature" }); const orderId = event.resource?.supplementary_data?.related_ids?.order_id; if (orderId && ["PAYMENT.CAPTURE.DENIED", "PAYMENT.CAPTURE.REFUNDED"].includes(event.event_type)) { const status = event.event_type.endsWith("REFUNDED") ? "refunded" : "denied"; const { data: payment } = await db.from("payments").update({ status }).eq("paypal_order_id", orderId).select().maybeSingle(); if (payment) await db.from("payment_events").insert({ payment_id: payment.id, user_id: payment.user_id, event_type: event.event_type, paypal_event_id: event.id, payload: event }); } response.status(200).json({ received: true }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Webhook processing failed" }); } }
export async function adminTrialOverview(_request: AuthRequest, response: Response) { try { response.json({ data: await trialAnalytics() }); } catch { response.status(500).json({ error: "Unable to retrieve trial analytics" }); } }
export async function adminTrialUsers(request: AuthRequest, response: Response) { try { response.json({ data: await membershipUsers(String(request.query.filter ?? "all") as never, String(request.query.query ?? "")) }); } catch { response.status(500).json({ error: "Unable to retrieve membership users" }); } }
export async function adminConvertUser(request: AuthRequest, response: Response) { try { response.json({ data: await convertUserToPro(String(request.params.userId), request.user!.id) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to convert membership" }); } }
export async function adminExtendTrial(request: AuthRequest, response: Response) { try { const days = Number(request.body?.days ?? 7); response.json({ data: await extendTrial(String(request.params.userId), days, request.user!.id) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to extend trial" }); } }
export async function adminEndTrial(request: AuthRequest, response: Response) { try { response.json({ data: await endTrial(String(request.params.userId), request.user!.id) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to end trial" }); } }
