import type { Response } from "express";
import { orchestrationSchema } from "../domain/music.js";
import type { AuthRequest } from "../middleware/auth.js";
import { orchestrateGeneration, voiceUploadPath } from "../services/orchestration.service.js";
import { requireSupabase } from "../config/supabase.js";
import { z } from "zod";
import { ArtistOriginalityViolationError } from "../services/artistInspiration/index.js";
import { MusicBrainValidationError } from "../services/musicBrain/index.js";

function generationErrorStatus(error: unknown) {
	if (error instanceof ArtistOriginalityViolationError || error instanceof MusicBrainValidationError) return 422;
	return 502;
}

const discreetServerError = "Server error. Please try again in a few minutes.";

export async function list(request: AuthRequest, response: Response) { try { const { data, error } = await requireSupabase().from("generations").select("*, generation_requests(prompt, kind, settings), generation_files(*)").eq("user_id", request.user!.id).order("created_at", { ascending: false }); if (error) throw error; response.json({ data }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to list generations" }); } }
export async function create(request: AuthRequest, response: Response) { const parsed = orchestrationSchema.safeParse(request.body); if (!parsed.success) return response.status(422).json({ error: "Invalid generation request", details: parsed.error.flatten() }); try { response.status(201).json({ data: await orchestrateGeneration(request.user!.id, parsed.data) }); } catch (error) { const status = generationErrorStatus(error); response.status(status).json({ error: status === 422 && error instanceof Error ? error.message : discreetServerError }); } }
export async function read(request: AuthRequest, response: Response) { try { const { data, error } = await requireSupabase().from("generations").select("*, generation_requests(prompt, kind, settings), generation_files(*)").eq("id", request.params.generationId).eq("user_id", request.user!.id).single(); if (error) return response.status(404).json({ error: "Generation not found" }); response.json({ data }); } catch { response.status(500).json({ error: "Unable to read generation" }); } }
export async function exports(request: AuthRequest, response: Response) { try { const db = requireSupabase(); const { data, error } = await db.from("generation_files").select("id, file_name, mime_type, storage_path").eq("generation_id", request.params.generationId).eq("user_id", request.user!.id); if (error) throw error; if (!data?.length) return response.status(404).json({ error: "Generation files not found" }); const files = [] as Array<{ id: string; fileName: string; mimeType: string; url: string; kind: "single" | "multi" | "package" }>; for (const file of data) { const { data: signed, error: signError } = await db.storage.from("midi-exports").createSignedUrl(file.storage_path, 900); if (signError) throw signError; files.push({ id: String(file.id), fileName: file.file_name, mimeType: file.mime_type, url: signed.signedUrl, kind: file.file_name.endsWith("-exports.zip") ? "package" : file.file_name.includes("-multitrack.") ? "multi" : "single" }); } response.json({ data: files }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load generation exports" }); } }
export async function remove(request: AuthRequest, response: Response) { try { const db = requireSupabase(); const { data: files } = await db.from("generation_files").select("storage_path").eq("generation_id", request.params.generationId).eq("user_id", request.user!.id); if (files?.length) { const paths = files.map((file) => file.storage_path); await db.storage.from("midi-exports").remove(paths); await db.from("downloads").update({ deleted_at: new Date().toISOString() }).eq("user_id", request.user!.id).in("storage_path", paths); } const { error } = await db.from("generations").delete().eq("id", request.params.generationId).eq("user_id", request.user!.id); if (error) throw error; response.status(204).end(); } catch { response.status(500).json({ error: "Unable to delete generation" }); } }
export async function voiceUpload(request: AuthRequest, response: Response) { const parsed = z.object({ fileName: z.string().min(1).max(255), mimeType: z.enum(["audio/wav", "audio/mpeg", "audio/mp4"]), sizeBytes: z.number().int().positive().max(25 * 1024 * 1024) }).safeParse(request.body); if (!parsed.success) return response.status(422).json({ error: "Invalid voice upload", details: parsed.error.flatten() }); try { const db = requireSupabase(); const path = voiceUploadPath(request.user!.id, parsed.data.fileName); const { data, error } = await db.storage.from("voice-uploads").createSignedUploadUrl(path); if (error) throw error; response.status(201).json({ data: { uploadUrl: data.signedUrl, token: data.token, storagePath: path, status: "accepted_for_transcription" } }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to prepare voice upload" }); } }
export async function favorite(request: AuthRequest, response: Response) { try { const { error } = await requireSupabase().from("favorites").upsert({ user_id: request.user!.id, generation_id: request.params.generationId }); if (error) throw error; response.status(204).end(); } catch { response.status(500).json({ error: "Unable to favorite generation" }); } }
export async function regenerate(request: AuthRequest, response: Response) { try { const db = requireSupabase(); const { data, error } = await db.from("generations").select("generation_requests(prompt, kind, settings)").eq("id", request.params.generationId).eq("user_id", request.user!.id).single(); if (error || !data?.generation_requests) return response.status(404).json({ error: "Generation not found" }); const source = data.generation_requests as unknown as { prompt: string; kind: string; settings: unknown }; const input = orchestrationSchema.parse({ ...(source.settings as object), prompt: source.prompt, kind: source.kind }); response.status(201).json({ data: await orchestrateGeneration(request.user!.id, input) }); } catch (error) { const status = generationErrorStatus(error); response.status(status).json({ error: status === 422 && error instanceof Error ? error.message : discreetServerError }); } }
