import type { Request, Response } from "express";
import { z } from "zod";
import type { AuthRequest } from "../middleware/auth.js";
import { sendPayout } from "../paypal/paypal.service.js";
import { adminCommissions, adminPayoutHistory, adminPayoutRequests, adminReferralOverview, adminReferrers, approvePayoutRequest, createPayoutRequest, loadReferralSettings, recordReferralTouch, referralActivity, referralDashboard, referralStats, rejectPayoutRequest, trackReferralClick, updateReferralSettings } from "../services/referral.service.js";

const clickSchema = z.object({ referralCode: z.string().trim().min(3).max(32), visitorSessionId: z.string().max(120).optional(), landingPath: z.string().max(300).optional(), deviceFingerprint: z.string().max(200).optional(), signupSource: z.string().max(120).optional() });
const payoutRequestSchema = z.object({ amount: z.number().positive().optional(), paypalEmail: z.string().email().optional() });
const shareSchema = z.object({ channel: z.string().max(80).optional(), target: z.string().max(160).optional() });
const settingsSchema = z.object({ enabled: z.boolean().optional(), defaultCommissionType: z.enum(["percentage", "flat"]).optional(), defaultCommissionRate: z.number().min(0).max(100).optional(), flatCommissionCents: z.number().int().min(0).optional(), minimumPayoutCents: z.number().int().min(100).optional(), eligibilityDelayDays: z.number().int().min(0).max(365).optional(), cookieDurationDays: z.number().int().min(1).max(365).optional(), referralExpirationDays: z.number().int().min(1).max(3650).optional(), allowSelfReferrals: z.boolean().optional(), allowMultipleReferrals: z.boolean().optional(), maximumCommissionPerUserCents: z.number().int().min(0).optional(), maximumPayoutPerMonthCents: z.number().int().min(0).optional(), automaticApproval: z.boolean().optional(), manualApproval: z.boolean().optional() });
const payoutDecisionSchema = z.object({ requestId: z.string().uuid(), notes: z.string().max(500).optional() });

function originFor(request: Request) { return String(request.headers.origin ?? `${request.protocol}://${request.get("host") ?? "midiflow.ai"}`); }
function clientIp(request: Request) { return request.headers["x-forwarded-for"]?.toString().split(",")[0]?.trim() ?? request.ip ?? null; }

export async function click(request: Request, response: Response) { try { const body = clickSchema.parse(request.body); response.status(201).json({ data: await trackReferralClick({ ...body, sourceIp: clientIp(request), userAgent: request.get("user-agent") ?? null }) }); } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : "Unable to track referral click" }); } }
export async function dashboard(request: AuthRequest, response: Response) { try { response.json({ data: await referralDashboard(request.user!.id, originFor(request)) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load referrals" }); } }
export async function stats(request: AuthRequest, response: Response) { try { response.json({ data: await referralStats(request.user!.id, originFor(request)) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load referral stats" }); } }
export async function activity(request: AuthRequest, response: Response) { try { response.json({ data: await referralActivity(request.user!.id, originFor(request)) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load referral activity" }); } }
export async function copy(request: AuthRequest, response: Response) { try { response.status(201).json({ data: await recordReferralTouch(request.user!.id, "copy", { origin: request.headers.origin ?? null }) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to record copy action" }); } }
export async function share(request: AuthRequest, response: Response) { try { response.status(201).json({ data: await recordReferralTouch(request.user!.id, "share", shareSchema.parse(request.body ?? {})) }); } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : "Unable to record share action" }); } }
export async function payoutRequest(request: AuthRequest, response: Response) { try { const body = payoutRequestSchema.parse(request.body ?? {}); response.status(201).json({ data: await createPayoutRequest(request.user!.id, { amountCents: body.amount !== undefined ? Math.round(body.amount * 100) : undefined, paypalEmail: body.paypalEmail }) }); } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : "Unable to create payout request" }); } }
export async function adminOverview(_request: AuthRequest, response: Response) { try { response.json({ data: await adminReferralOverview() }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load admin referrals" }); } }
export async function adminReferrerList(_request: AuthRequest, response: Response) { try { response.json({ data: await adminReferrers() }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load referrers" }); } }
export async function adminCommissionList(request: AuthRequest, response: Response) { try { response.json({ data: await adminCommissions({ status: String(request.query.status ?? "all"), query: String(request.query.query ?? "") }) }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load commissions" }); } }
export async function adminPayoutRequestList(_request: AuthRequest, response: Response) { try { response.json({ data: await adminPayoutRequests() }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load payout requests" }); } }
export async function adminPayoutHistoryList(_request: AuthRequest, response: Response) { try { response.json({ data: await adminPayoutHistory() }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load payout history" }); } }
export async function adminSettingsGet(_request: AuthRequest, response: Response) { try { response.json({ data: await loadReferralSettings() }); } catch (error) { response.status(500).json({ error: error instanceof Error ? error.message : "Unable to load referral settings" }); } }
export async function adminSettings(request: AuthRequest, response: Response) { try { response.json({ data: await updateReferralSettings(settingsSchema.parse(request.body ?? {})) }); } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : "Unable to update referral settings" }); } }
export async function adminApprovePayout(request: AuthRequest, response: Response) { try { const body = payoutDecisionSchema.parse(request.body ?? {}); response.json({ data: await approvePayoutRequest(body.requestId, request.user!.id, sendPayout) }); } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : "Unable to approve payout request" }); } }
export async function adminRejectPayout(request: AuthRequest, response: Response) { try { const body = payoutDecisionSchema.parse(request.body ?? {}); response.json({ data: await rejectPayoutRequest(body.requestId, request.user!.id, body.notes) }); } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : "Unable to reject payout request" }); } }