import type { OrchestrationInput } from "../domain/music.js";

const defaults = { tempo: 120, scale: "Major", key: "C Major", mood: "balanced" };
export function buildMusicPrompt(input: OrchestrationInput, referencePrompt = "") {
  const tempo = input.tempo ?? defaults.tempo;
  const scale = input.scale ?? defaults.scale;
  const key = input.key ?? defaults.key;
  const guitarMelodyRequest = /\b(spanish|flamenco|nylon|guitar)\b/i.test(input.prompt) && /\b(chord|harmony|progression|melody)\b/i.test(input.prompt);
  const fullFormGuidance = `The melody must span the complete ${input.lengthBars}-bar form: introduce a motif in bars 1-2, develop it in bars 3-4, create contrast or call-and-response in bars 5-6, and return with variation and a resolved phrase ending in bars 7-${input.lengthBars}. Place meaningful notes and rests across the form; never stop after the first phrase. Chord progression entries must cover every bar through bar ${input.lengthBars}.`;
    const guitarChordGuidance = `Priority order: curated MIDI references first, explicit user request second, artist/genre flavor third. ${fullFormGuidance} Aim for very strong reference-style similarity through shared musical vocabulary: closely match the reference pocket, rhythmic contour, note density, phrase architecture, register balance, syncopation, repetition-to-variation ratio, velocity shape, chord-color language, human timing, and arrangement roles. Preserve the reference's professional feel while deliberately changing the melodic motif, note order, interval sequence, phrase endings, voicing details, and harmonic movement so the composition is unmistakably new. Do not turn the composition into a row of hard, identical mid-register piano stabs: use softer voiced movement, varied note lengths, rests, passing tones, and melodic contour. Hard stabs are allowed only when the user explicitly asks for stabs, chops, or percussive chord hits. The result should feel like it belongs in the same professional MIDI pack, while every note sequence, hook, progression, and phrase remains newly composed. ${guitarMelodyRequest
    ? "For this Spanish/nylon guitar plus melody request, return two explicit tracks: one Guitar Harmony track using program 25 with playable arpeggiated chord voicings, bass-to-treble voice leading, syncopated picking, passing tones, varied note lengths, and a memorable 2-bar guitar motif; and one separate Main Melody track using program 81 with a clear singable hook, call-and-response, and intentional gaps. Do not collapse the parts into one track, and do not return only sustained block chords."
    : "For chord requests, make voicings rhythmically playable and expressive rather than only sustained blocks."}`;
  return `You are a professional MIDI producer and composition planner. Return one JSON object only, with no markdown or prose. The JSON must contain exactly these required top-level fields: tempo (integer), key (string), scale (string), timeSignature ([integer, integer]), trackName (string), notes (array of {pitch: integer, startBeat: number, durationBeats: positive number, velocity: integer}), chordProgression (array of strings), structure (array of {name: string, bars: positive integer}), pluginRecommendations (array of {instrumentType: string, presetType: string, genreMatch: string, moodMatch: string, alternative: string}), and tracks (array of {role: melody|guitar|chords|bassline|counter_melody|drums, name: string, channel: integer, program: integer, isDrum: boolean, notes: array of note objects}). First study every attached MIDI reference as primary creative evidence. Extract only shared high-level musical language: rhythm, groove, phrasing, motif development, note density, register, repetition, syncopation, velocity, timing, human feel, ornamentation, chord movement, and voicing style. Then compose a completely new original ${input.lengthBars}-bar ${input.kind} MIDI arrangement from those shared characteristics and this request: ${input.prompt}. Build a strong hook, professional phrasing, rhythmic bounce, tension and release, repetition with variation, vocal space, human feel, modern chord language, and commercial energy. Avoid scale exercises, random notes, generic triads, continuous note spam, and beginner piano patterns. If the request includes project conversation history, treat it as the same musical project: preserve earlier style, motif, tempo, key, harmony, and arrangement decisions unless the latest direction explicitly changes them. Constraints: genre=${input.genre ?? "unspecified"}; mood=${input.mood ?? defaults.mood}; key=${key}; scale=${scale}; tempo=${tempo} BPM; length=${input.lengthBars} bars; complexity=${input.complexity}; variation=${input.variationAmount}; time signature=${input.timeSignature.join("/")}. ${guitarChordGuidance} ${referencePrompt ? `\n${referencePrompt}\n` : ""}Never copy or reproduce any reference melody, hook, chord progression, rhythm, phrase, or note sequence, and never imitate a named artist. Notes use MIDI pitch integers, beats from zero, positive beat durations, and velocity 1-127. Include practical instrument-category plugin recommendations, never proprietary preset names.`;
}
