import type { OrchestrationInput } from "../domain/music.js";

const defaults = { tempo: 120, scale: "Major", key: "C Major", mood: "balanced" };
export function buildMusicPrompt(input: OrchestrationInput, referencePrompt = "") {
  const tempo = input.tempo ?? defaults.tempo;
  const scale = input.scale ?? defaults.scale;
  const key = input.key ?? defaults.key;
  return `You are a music composition planner. Return one JSON object only, with no markdown or prose. The JSON must contain exactly these required top-level fields: tempo (integer), key (string), scale (string), timeSignature ([integer, integer]), trackName (string), notes (array of {pitch: integer, startBeat: number, durationBeats: positive number, velocity: integer}), chordProgression (array of strings), structure (array of {name: string, bars: positive integer}), and pluginRecommendations (array of {instrumentType: string, presetType: string, genreMatch: string, moodMatch: string, alternative: string}). Compose an original ${input.kind} MIDI arrangement from this request: ${input.prompt}. If the request includes project conversation history, treat it as the same musical project: preserve earlier style, motif, tempo, key, harmony, and arrangement decisions unless the latest direction explicitly changes them. Constraints: genre=${input.genre ?? "unspecified"}; mood=${input.mood ?? defaults.mood}; key=${key}; scale=${scale}; tempo=${tempo} BPM; length=${input.lengthBars} bars; complexity=${input.complexity}; variation=${input.variationAmount}; time signature=${input.timeSignature.join("/")}. ${referencePrompt ? `\n${referencePrompt}\n` : ""}Never imitate named artists or copy reference files. Notes use MIDI pitch integers, beats from zero, positive beat durations, and velocity 1-127. Include practical instrument-category plugin recommendations, never proprietary preset names.`;
}
