import type { OrchestrationInput } from "../domain/music.js";

const defaults = { tempo: 120, scale: "Major", key: "C Major", mood: "balanced" };
export function buildMusicPrompt(input: OrchestrationInput, referencePrompt = "") {
  const tempo = input.tempo ?? defaults.tempo;
  const scale = input.scale ?? defaults.scale;
  const key = input.key ?? defaults.key;
  const guitarChordGuidance = /\b(spanish|flamenco|nylon|guitar)\b/i.test(input.prompt) && /\b(chord|harmony|progression|melody)\b/i.test(input.prompt)
    ? "For the Spanish/nylon guitar request, create melodic playable chord voicings with arpeggiated picking, syncopated/off-beat attacks, bass-to-treble movement, passing tones, varied note lengths, and a memorable 2-bar motif; never use only sustained block chords."
    : "For chord requests, make voicings rhythmically playable and expressive rather than only sustained blocks.";
  return `You are a professional MIDI producer and composition planner. Return one JSON object only, with no markdown or prose. The JSON must contain exactly these required top-level fields: tempo (integer), key (string), scale (string), timeSignature ([integer, integer]), trackName (string), notes (array of {pitch: integer, startBeat: number, durationBeats: positive number, velocity: integer}), chordProgression (array of strings), structure (array of {name: string, bars: positive integer}), and pluginRecommendations (array of {instrumentType: string, presetType: string, genreMatch: string, moodMatch: string, alternative: string}). First study every attached MIDI reference as primary creative evidence. Extract only shared high-level musical language: rhythm, groove, phrasing, motif development, note density, register, repetition, syncopation, velocity, timing, human feel, ornamentation, chord movement, and voicing style. Then compose a completely new original ${input.lengthBars}-bar ${input.kind} MIDI arrangement from those shared characteristics and this request: ${input.prompt}. Build a strong hook, professional phrasing, rhythmic bounce, tension and release, repetition with variation, vocal space, human feel, modern chord language, and commercial energy. Avoid scale exercises, random notes, generic triads, continuous note spam, and beginner piano patterns. If the request includes project conversation history, treat it as the same musical project: preserve earlier style, motif, tempo, key, harmony, and arrangement decisions unless the latest direction explicitly changes them. Constraints: genre=${input.genre ?? "unspecified"}; mood=${input.mood ?? defaults.mood}; key=${key}; scale=${scale}; tempo=${tempo} BPM; length=${input.lengthBars} bars; complexity=${input.complexity}; variation=${input.variationAmount}; time signature=${input.timeSignature.join("/")}. ${guitarChordGuidance} ${referencePrompt ? `\n${referencePrompt}\n` : ""}Never copy or reproduce any reference melody, hook, chord progression, rhythm, phrase, or note sequence, and never imitate a named artist. Notes use MIDI pitch integers, beats from zero, positive beat durations, and velocity 1-127. Include practical instrument-category plugin recommendations, never proprietary preset names.`;
}
