export type StyleVector = {
  tempo: { min: number; max: number; preferred: number };
  melodyDensity: number;
  noteDensity: number;
  phraseLength: number;
  motifRepetition: number;
  syncopation: number;
  rhythmicComplexity: number;
  chordComplexity: number;
  register: "low" | "mid" | "high" | "wide";
  octaveUsage: string;
  energy: number;
  instruments: Record<string, number>;
};

export type JamaicanArtistProfile = StyleVector & {
  artistId: string;
  artistName: string;
  aliases: string[];
  country: string;
  primaryGenres: string[];
  secondaryGenres: string[];
  subgenres: string[];
  era: string;
  keyTendencies: string[];
  scaleTendencies: string[];
  harmonicCharacteristics: string[];
  melodicCharacteristics: string[];
  rhythmicCharacteristics: string[];
  bassCharacteristics: string[];
  instrumentPreferences: string[];
  commonInstruments: string[];
  tensionAndRelease: string;
  emotionalCharacteristics: string[];
  songStructureTendencies: string[];
  productionCharacteristics: string[];
  referencePackWeights: Record<string, number>;
  confidenceScore: number;
  sourceMetadata: { source: string; sourceType: string; licenseStatus: string };
  songs: JamaicanSongMetadata[];
  status: "pending" | "verified" | "rejected" | "needs_review";
  lastVerified: string | null;
};

export type JamaicanSongMetadata = {
  songId: string;
  artistId: string;
  title: string;
  releaseYear: number | null;
  genre: string;
  subgenre: string;
  bpm: number | null;
  key: string | null;
  mode: string | null;
  durationSeconds: number | null;
  instrumentation: string[];
  musicalFeatures: string[];
  source: string;
  sourceType: "curated_metadata";
  sourceUrl: string | null;
  licenseStatus: "metadata_only";
  confidence: number;
  status: "pending" | "verified" | "rejected" | "needs_review";
  lastVerified: string | null;
};

export type JamaicanGenreProfile = {
  genreId: string;
  genreName: string;
  tempoRange: { min: number; max: number; preferred: number };
  keyTendencies: string[];
  scaleTendencies: string[];
  rhythmCharacteristics: string[];
  melodyDensity: number;
  chordTendencies: string[];
  bassTendencies: string[];
  instrumentation: string[];
  phraseStructures: string[];
  syncopation: number;
  energy: number;
  productionCharacteristics: string[];
  referencePackWeights: Record<string, number>;
};

export type JamaicanGenerationContext = {
  artistProfile: Partial<JamaicanArtistProfile> | null;
  genreProfile: JamaicanGenreProfile | null;
  instrumentProfile: { name: string; weight: number } | null;
  userPreferences: { prompt: string; mood?: string; tempo?: number; instrument?: string };
  referenceFeatures: Array<{ pack: string; weight: number }>;
  generationConstraints: {
    originalComposition: true;
    noLyrics: true;
    noKnownSongMelody: true;
    explicitUserDirectionWins: true;
    influenceWeights: { artist: number; genre: number; instrument: number; reference: number };
  };
};

export type AnalyzedSongStyle = {
  tempo?: number | null;
  confidence: number;
  melodyDensity?: number;
  harmonicDensity?: number;
  rhythmicDensity?: number;
  syncopation?: number;
  motifRepetition?: number;
  phraseLength?: number;
  energy?: number;
  register?: "low" | "mid" | "high" | "wide";
  instruments?: string[];
};

export type AggregatedArtistStyle = {
  songCount: number;
  tempo: { min: number | null; max: number | null; preferred: number | null };
  averages: Record<string, number | null>;
  frequencies: Record<string, number>;
  instrumentWeights: Record<string, number>;
  confidence: number;
};

const sourceMetadata = { source: "MidiFlow curated knowledge base", sourceType: "curated", licenseStatus: "metadata_only" };
const song = (artistId: string, title: string, releaseYear: number, genre: string, subgenre: string, features: string[]): JamaicanSongMetadata => ({
  songId: `${artistId}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  artistId,
  title,
  releaseYear,
  genre,
  subgenre,
  bpm: null,
  key: null,
  mode: null,
  durationSeconds: null,
  instrumentation: [],
  musicalFeatures: features,
  source: sourceMetadata.source,
  sourceType: "curated_metadata",
  sourceUrl: null,
  licenseStatus: "metadata_only",
  confidence: 0.72,
  status: "pending",
  lastVerified: null,
});

const artist = (input: Omit<JamaicanArtistProfile, "sourceMetadata" | "instruments" | "confidenceScore" | "status" | "lastVerified">): JamaicanArtistProfile => ({
  ...input,
  instruments: Object.fromEntries(input.instrumentPreferences.map((instrument, index) => [instrument, Number(Math.max(0.45, 1 - index * 0.12).toFixed(2))])),
  confidenceScore: 0.72,
  sourceMetadata,
  status: "pending",
  lastVerified: null,
});

export const JAMAICAN_ARTIST_PROFILES: JamaicanArtistProfile[] = [
  artist({ artistId: "shenseea", artistName: "Shenseea", aliases: ["shenseea"], country: "Jamaica", primaryGenres: ["Dancehall", "Pop Dancehall"], secondaryGenres: ["Afrobeats", "R&B"], subgenres: ["Pop Dancehall", "Crossover Dancehall"], era: "2010s-present", tempo: { min: 94, max: 112, preferred: 102 }, keyTendencies: ["minor", "bright modal"], scaleTendencies: ["natural minor", "major pentatonic"], harmonicCharacteristics: ["compact loops", "clear tonic focus"], melodicCharacteristics: ["catchy vocal-friendly hooks", "short call-and-response cells"], rhythmicCharacteristics: ["tight dembow syncopation", "off-beat hook accents"], bassCharacteristics: ["rounded syncopated bass", "short phrase answers"], instrumentPreferences: ["bright piano", "pluck", "guitar", "bell"], commonInstruments: ["Piano", "Pluck", "Guitar", "Bell", "Bass"], melodyDensity: 0.56, noteDensity: 0.5, phraseLength: 2, motifRepetition: 0.79, syncopation: 0.69, rhythmicComplexity: 0.66, chordComplexity: 0.4, register: "mid", octaveUsage: "occasional hook octave lift", tensionAndRelease: "short anticipation into hook resolution", emotionalCharacteristics: ["confident", "playful", "romantic"], energy: 0.83, songStructureTendencies: ["intro", "verse", "pre-hook", "hook", "verse", "hook"], productionCharacteristics: ["clean drums", "bright top line", "vocal space", "controlled low end"], referencePackWeights: { "Dancehall & Pop Dancehall": 0.9, "Modern Trap Dancehall": 0.55, "Afrobeat Guitar": 0.45 }, songs: [song("shenseea", "Blessed", 2017, "Dancehall", "Pop Dancehall", ["hook-led", "bright", "danceable"]), song("shenseea", "Loodi", 2017, "Dancehall", "Pop Dancehall", ["syncopated", "club-focused", "call-and-response"]), song("shenseea", "ShenYeng Anthem", 2019, "Dancehall", "Pop Dancehall", ["anthemic", "rhythmic hook", "high energy"]), song("shenseea", "Run Run", 2021, "Dancehall", "Modern Dancehall", ["sparse groove", "vocal space", "minor color"]), song("shenseea", "Hit & Run", 2024, "Dancehall", "Pop Dancehall", ["percussive", "catchy", "crossover"]) ] }),
  artist({ artistId: "spice", artistName: "Spice", aliases: ["spice", "queen of dancehall"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Reggae", "Pop Dancehall"], subgenres: ["Classic Dancehall", "Conscious Dancehall"], era: "2000s-present", tempo: { min: 90, max: 108, preferred: 99 }, keyTendencies: ["minor", "major"], scaleTendencies: ["natural minor", "mixolydian"], harmonicCharacteristics: ["direct repetitive harmony", "strong tonal anchors"], melodicCharacteristics: ["chant-like hooks", "rhythmic vocal cells"], rhythmicCharacteristics: ["dembow pocket", "accented off-beats"], bassCharacteristics: ["firm root-led movement", "danceable syncopation"], instrumentPreferences: ["piano", "organ", "guitar", "percussion"], commonInstruments: ["Piano", "Organ", "Guitar", "Bass", "Percussion"], melodyDensity: 0.48, noteDensity: 0.44, phraseLength: 2, motifRepetition: 0.84, syncopation: 0.72, rhythmicComplexity: 0.68, chordComplexity: 0.3, register: "mid", octaveUsage: "stable mid register with hook doubling", tensionAndRelease: "repetition and rhythmic dropouts", emotionalCharacteristics: ["assertive", "celebratory", "direct"], energy: 0.86, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "bridge"], productionCharacteristics: ["strong drum pocket", "prominent bass", "dry rhythmic accents", "vocal-forward arrangement"], referencePackWeights: { "Dancehall & Pop Dancehall": 1, "Emotional Dancehall MIDI": 0.35 }, songs: [song("spice", "So Mi Like It", 2014, "Dancehall", "Classic Dancehall", ["chant hook", "syncopated", "club energy"]), song("spice", "Needle Eye", 2015, "Dancehall", "Classic Dancehall", ["repetitive hook", "percussive", "bouncy"]), song("spice", "Romping Shop", 2009, "Dancehall", "Classic Dancehall", ["call-and-response", "direct harmony", "dance groove"]), song("spice", "Go Down Deh", 2021, "Dancehall", "Pop Dancehall", ["anthemic", "bright", "high energy"]), song("spice", "Differ", 2020, "Dancehall", "Modern Dancehall", ["sparse", "assertive", "bass-led"]) ] }),
  artist({ artistId: "mavado", artistName: "Mavado", aliases: ["mavado", "gully gawd"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Reggae", "Trap Dancehall"], subgenres: ["Dark Dancehall", "Gully Dancehall"], era: "2000s-present", tempo: { min: 88, max: 106, preferred: 98 }, keyTendencies: ["minor", "modal"], scaleTendencies: ["natural minor", "phrygian"], harmonicCharacteristics: ["dark loops", "drone-like tonal centers"], melodicCharacteristics: ["anthemic minor hooks", "wide vocal contour"], rhythmicCharacteristics: ["steady dembow", "dramatic syncopated fills"], bassCharacteristics: ["deep sustained roots", "phrase-ending movement"], instrumentPreferences: ["dark piano", "strings", "bell", "guitar"], commonInstruments: ["Dark Piano", "Strings", "Bell", "Guitar", "808"], melodyDensity: 0.42, noteDensity: 0.4, phraseLength: 4, motifRepetition: 0.74, syncopation: 0.61, rhythmicComplexity: 0.6, chordComplexity: 0.42, register: "mid", octaveUsage: "wide hook doubles and occasional low responses", tensionAndRelease: "sustained minor tension with chorus release", emotionalCharacteristics: ["dark", "melancholic", "triumphant"], energy: 0.78, songStructureTendencies: ["atmospheric intro", "verse", "anthem hook", "verse", "hook"], productionCharacteristics: ["dark atmosphere", "wide low end", "dramatic transitions", "space around vocal"], referencePackWeights: { "Dark Piano": 0.85, "Emotional Dancehall MIDI": 0.7, "Modern Trap Dancehall": 0.7 }, songs: [song("mavado", "Real McKoy", 2007, "Dancehall", "Dark Dancehall", ["minor", "anthemic", "dramatic"]), song("mavado", "So Special", 2008, "Dancehall", "Dark Dancehall", ["melancholic", "wide hook", "sustained tone"]), song("mavado", "I'm On The Rock", 2009, "Dancehall", "Dark Dancehall", ["anthemic", "bass-led", "minor"]), song("mavado", "Progress", 2017, "Dancehall", "Conscious Dancehall", ["reflective", "steady groove", "vocal space"]), song("mavado", "Big League", 2010, "Dancehall", "Modern Dancehall", ["assertive", "club rhythm", "repetitive hook"]) ] }),
  artist({ artistId: "armanii", artistName: "Armanii", aliases: ["armanii"], country: "Jamaica", primaryGenres: ["Modern Trap Dancehall"], secondaryGenres: ["Dancehall", "R&B"], subgenres: ["Emotional Trap Dancehall"], era: "2020s", tempo: { min: 92, max: 108, preferred: 100 }, keyTendencies: ["minor", "minor 7 color"], scaleTendencies: ["natural minor", "dorian"], harmonicCharacteristics: ["spacious minor loops", "soft extensions"], melodicCharacteristics: ["melodic vocal pockets", "short emotional motifs"], rhythmicCharacteristics: ["laid-back syncopation", "trap hat support"], bassCharacteristics: ["sub movement under gaps", "sparse 808 accents"], instrumentPreferences: ["emotional piano", "guitar", "pad", "bell"], commonInstruments: ["Emotional Piano", "Guitar", "Pad", "Bell", "808"], melodyDensity: 0.4, noteDensity: 0.38, phraseLength: 4, motifRepetition: 0.76, syncopation: 0.58, rhythmicComplexity: 0.56, chordComplexity: 0.48, register: "mid", octaveUsage: "selective high answer notes", tensionAndRelease: "delayed resolution through held color tones", emotionalCharacteristics: ["emotional", "intimate", "moody"], energy: 0.62, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "outro"], productionCharacteristics: ["wide pads", "soft piano", "restrained drums", "vocal space"], referencePackWeights: { "Emotional Dancehall MIDI": 0.9, "Trap Emotional Piano": 0.75, "Emotional Guitar MIDI": 0.7 }, songs: [song("armanii", "Toxic", 2022, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["emotional", "sparse", "minor"]), song("armanii", "Yea Yea", 2021, "Dancehall", "Modern Dancehall", ["melodic", "laid-back", "hook-led"]), song("armanii", "Una", 2023, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["spacious", "vocal-friendly", "soft harmony"]), song("armanii", "Mood", 2022, "Dancehall", "Emotional Dancehall", ["intimate", "syncopated", "minor"]), song("armanii", "Falling", 2024, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["atmospheric", "delayed resolution", "sparse"]) ] }),
  artist({ artistId: "valiant", artistName: "Valiant", aliases: ["valiant"], country: "Jamaica", primaryGenres: ["Modern Trap Dancehall"], secondaryGenres: ["Dancehall", "Pop Dancehall"], subgenres: ["Bouncy Trap Dancehall"], era: "2020s", tempo: { min: 96, max: 112, preferred: 104 }, keyTendencies: ["minor", "bright minor"], scaleTendencies: ["natural minor", "minor pentatonic"], harmonicCharacteristics: ["minimal loops", "quick turnaround"], melodicCharacteristics: ["bouncy piano hooks", "short repeated motifs"], rhythmicCharacteristics: ["skippy dembow", "anticipations", "hat-assisted bounce"], bassCharacteristics: ["punchy 808", "root and fifth accents"], instrumentPreferences: ["bright piano", "bell", "808", "pluck"], commonInstruments: ["Bright Piano", "Bell", "808", "Pluck", "Percussion"], melodyDensity: 0.5, noteDensity: 0.47, phraseLength: 2, motifRepetition: 0.86, syncopation: 0.76, rhythmicComplexity: 0.74, chordComplexity: 0.32, register: "mid", octaveUsage: "short high accents around hook", tensionAndRelease: "anticipation into clipped hook endings", emotionalCharacteristics: ["energetic", "confident", "playful"], energy: 0.9, songStructureTendencies: ["short intro", "hook", "verse", "hook", "outro"], productionCharacteristics: ["punchy drums", "bright piano", "tight bass", "high vocal space"], referencePackWeights: { "Modern Trap Dancehall": 1, "Dancehall & Pop Dancehall": 0.75, "Trap 808 MIDI": 0.55 }, songs: [song("valiant", "Dunce", 2023, "Modern Trap Dancehall", "Bouncy Trap Dancehall", ["bouncy", "piano hook", "high repetition"]), song("valiant", "Speed Off", 2023, "Dancehall", "Modern Dancehall", ["skippy", "club energy", "syncopated"]), song("valiant", "North Sq", 2022, "Modern Trap Dancehall", "Bouncy Trap Dancehall", ["minimal", "808-led", "short motif"]), song("valiant", "Expensive", 2023, "Dancehall", "Pop Dancehall", ["bright", "catchy", "punchy"]), song("valiant", "Killa", 2024, "Modern Trap Dancehall", "Bouncy Trap Dancehall", ["energetic", "repetitive", "percussive"]) ] }),
  artist({ artistId: "merkz", artistName: "Merkz", aliases: ["merkz"], country: "Jamaica", primaryGenres: ["Modern Trap Dancehall"], secondaryGenres: ["Dancehall", "Trap"], subgenres: ["Street Trap Dancehall"], era: "2020s", tempo: { min: 94, max: 110, preferred: 101 }, keyTendencies: ["minor", "dark modal"], scaleTendencies: ["natural minor", "phrygian"], harmonicCharacteristics: ["sparse minor ostinatos", "low chord turnover"], melodicCharacteristics: ["dark short motifs", "rhythmic lead fragments"], rhythmicCharacteristics: ["hard bounce", "syncopated rests", "trap subdivisions"], bassCharacteristics: ["short 808 punches", "sliding phrase turns"], instrumentPreferences: ["dark piano", "bell", "808", "pluck"], commonInstruments: ["Dark Piano", "Bell", "808", "Pluck", "Percussion"], melodyDensity: 0.37, noteDensity: 0.36, phraseLength: 2, motifRepetition: 0.82, syncopation: 0.72, rhythmicComplexity: 0.72, chordComplexity: 0.28, register: "mid", octaveUsage: "low lead with occasional high punctuation", tensionAndRelease: "rests and bass drops create release", emotionalCharacteristics: ["dark", "street", "urgent"], energy: 0.84, songStructureTendencies: ["intro", "hook", "verse", "hook", "bridge", "hook"], productionCharacteristics: ["hard transient drums", "dark keys", "wide 808", "sparse arrangement"], referencePackWeights: { "Modern Trap Dancehall": 0.95, "Dark Trap MIDI": 0.75, "Trap 808 MIDI": 0.7 }, songs: [song("merkz", "Different", 2023, "Modern Trap Dancehall", "Street Trap Dancehall", ["dark", "sparse", "hard bounce"]), song("merkz", "Pain", 2022, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["minor", "808-led", "repetitive"]), song("merkz", "Badness", 2023, "Dancehall", "Street Dancehall", ["aggressive", "syncopated", "short hook"]), song("merkz", "Outside", 2024, "Modern Trap Dancehall", "Street Trap Dancehall", ["urgent", "percussive", "low register"]), song("merkz", "No Pressure", 2022, "Trap", "Trap Dancehall", ["sparse", "dark piano", "bass punches"]) ] }),
  artist({ artistId: "popcaan", artistName: "Popcaan", aliases: ["popcaan", "unruly"], country: "Jamaica", primaryGenres: ["Dancehall", "Afrobeats"], secondaryGenres: ["Reggae", "Pop Dancehall"], subgenres: ["Melodic Dancehall", "Afro-Dancehall"], era: "2000s-present", tempo: { min: 90, max: 108, preferred: 100 }, keyTendencies: ["major", "minor", "modal"], scaleTendencies: ["major pentatonic", "natural minor", "mixolydian"], harmonicCharacteristics: ["warm repeating loops", "simple melodic harmony"], melodicCharacteristics: ["melodic hooks", "circular vocal phrases"], rhythmicCharacteristics: ["rolling dembow", "laid-back off-beats"], bassCharacteristics: ["melodic round bass", "syncopated roots"], instrumentPreferences: ["guitar", "keys", "pluck", "bell"], commonInstruments: ["Guitar", "Keys", "Pluck", "Bell", "Bass"], melodyDensity: 0.54, noteDensity: 0.5, phraseLength: 4, motifRepetition: 0.77, syncopation: 0.67, rhythmicComplexity: 0.61, chordComplexity: 0.42, register: "mid", octaveUsage: "melodic octave answers", tensionAndRelease: "circular phrases with gentle turnarounds", emotionalCharacteristics: ["warm", "dreamy", "confident"], energy: 0.76, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "outro"], productionCharacteristics: ["warm guitar", "rolling percussion", "melodic bass", "open vocal space"], referencePackWeights: { "Dancehall & Pop Dancehall": 0.9, "Afrobeat Guitar": 0.8, "Afro Acoustic MIDI": 0.65 }, songs: [song("popcaan", "Everything Nice", 2014, "Dancehall", "Melodic Dancehall", ["warm", "melodic", "guitar-led"]), song("popcaan", "Family", 2014, "Dancehall", "Melodic Dancehall", ["reflective", "circular", "vocal-friendly"]), song("popcaan", "Party Shot", 2013, "Dancehall", "Classic Dancehall", ["club", "syncopated", "repetitive"]), song("popcaan", "Firm and Strong", 2011, "Dancehall", "Melodic Dancehall", ["anthemic", "minor color", "bass movement"]), song("popcaan", "Body So Good", 2018, "Dancehall", "Pop Dancehall", ["warm", "romantic", "rolling groove"]) ] }),
  artist({ artistId: "tommy-lee-sparta", artistName: "Tommy Lee Sparta", aliases: ["tommy lee sparta", "tommy lee", "sparta"], country: "Jamaica", primaryGenres: ["Dark Dancehall"], secondaryGenres: ["Trap Dancehall", "Reggae"], subgenres: ["Gothic Dancehall", "Dark Dancehall"], era: "2000s-present", tempo: { min: 88, max: 106, preferred: 98 }, keyTendencies: ["minor", "phrygian"], scaleTendencies: ["natural minor", "phrygian", "harmonic minor"], harmonicCharacteristics: ["dark drones", "minor ostinatos", "suspended tension"], melodicCharacteristics: ["haunting motifs", "dramatic leaps", "chant responses"], rhythmicCharacteristics: ["heavy dembow", "stark gaps", "dramatic fills"], bassCharacteristics: ["sub-heavy roots", "descending turnarounds"], instrumentPreferences: ["dark piano", "strings", "bell", "808", "pad"], commonInstruments: ["Dark Piano", "Strings", "Bell", "808", "Pad"], melodyDensity: 0.35, noteDensity: 0.32, phraseLength: 4, motifRepetition: 0.8, syncopation: 0.59, rhythmicComplexity: 0.62, chordComplexity: 0.45, register: "mid", octaveUsage: "wide dramatic range", tensionAndRelease: "long dark tension against sudden hook release", emotionalCharacteristics: ["haunting", "menacing", "cinematic"], energy: 0.81, songStructureTendencies: ["dark intro", "verse", "hook", "verse", "hook", "outro"], productionCharacteristics: ["ominous keys", "heavy sub", "dramatic space", "cinematic transitions"], referencePackWeights: { "Dark Piano": 1, "Dark Trap MIDI": 0.85, "Emotional Dancehall MIDI": 0.55 }, songs: [song("tommy-lee-sparta", "Psycho", 2012, "Dancehall", "Gothic Dancehall", ["haunting", "minor", "dramatic"]), song("tommy-lee-sparta", "Uncle Demon", 2013, "Dancehall", "Gothic Dancehall", ["dark", "chant-like", "heavy bass"]), song("tommy-lee-sparta", "Spartan Soldier", 2011, "Dancehall", "Dark Dancehall", ["anthemic", "stark gaps", "minor"]), song("tommy-lee-sparta", "Rich Badness", 2012, "Dancehall", "Dark Dancehall", ["menacing", "repetitive", "dembow"]), song("tommy-lee-sparta", "Buss It", 2014, "Dancehall", "Dark Dancehall", ["energetic", "percussive", "hook-led"]) ] }),
  artist({ artistId: "beenie-man", artistName: "Beenie Man", aliases: ["beenie man", "king of dancehall"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Reggae", "Pop Dancehall"], subgenres: ["Classic Dancehall", "Digital Dancehall"], era: "1990s-present", tempo: { min: 88, max: 110, preferred: 100 }, keyTendencies: ["major", "minor", "mixolydian"], scaleTendencies: ["major pentatonic", "mixolydian", "natural minor"], harmonicCharacteristics: ["direct loops", "bright tonal punctuation"], melodicCharacteristics: ["rhythmic chants", "call-and-response", "short hooks"], rhythmicCharacteristics: ["precise dembow", "busy off-beat activity"], bassCharacteristics: ["active dance bass", "root-fifth punctuation"], instrumentPreferences: ["organ", "piano", "guitar", "brass", "percussion"], commonInstruments: ["Organ", "Piano", "Guitar", "Brass", "Percussion"], melodyDensity: 0.57, noteDensity: 0.53, phraseLength: 2, motifRepetition: 0.82, syncopation: 0.77, rhythmicComplexity: 0.72, chordComplexity: 0.34, register: "mid", octaveUsage: "rhythmic doubles across registers", tensionAndRelease: "frequent call-and-response resets", emotionalCharacteristics: ["celebratory", "confident", "playful"], energy: 0.88, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "bridge"], productionCharacteristics: ["crisp percussion", "active bass", "bright accents", "dense but vocal-aware groove"], referencePackWeights: { "Dancehall & Pop Dancehall": 1, "Afrobeat Chords": 0.45 }, songs: [song("beenie-man", "Who Am I", 1997, "Dancehall", "Digital Dancehall", ["chant hook", "bright", "call-and-response"]), song("beenie-man", "King of the Dancehall", 2004, "Dancehall", "Classic Dancehall", ["anthemic", "rhythmic", "high energy"]), song("beenie-man", "Dude", 2004, "Dancehall", "Pop Dancehall", ["catchy", "syncopated", "club"]), song("beenie-man", "Romie", 2000, "Dancehall", "Classic Dancehall", ["melodic", "repetitive", "vocal-led"]), song("beenie-man", "Girls", 2004, "Dancehall", "Pop Dancehall", ["bright", "bouncy", "hook-led"]) ] }),
  artist({ artistId: "bounty-killer", artistName: "Bounty Killer", aliases: ["bounty killer", "bounty"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Reggae", "Hip Hop"], subgenres: ["Hardcore Dancehall", "Conscious Dancehall"], era: "1990s-present", tempo: { min: 86, max: 106, preferred: 96 }, keyTendencies: ["minor", "modal"], scaleTendencies: ["natural minor", "dorian"], harmonicCharacteristics: ["stark loops", "low harmonic turnover"], melodicCharacteristics: ["forceful rhythmic phrases", "anthemic chants"], rhythmicCharacteristics: ["hard syncopation", "staccato accents", "dramatic stops"], bassCharacteristics: ["strong root hits", "space between bass phrases"], instrumentPreferences: ["dark piano", "brass", "organ", "percussion"], commonInstruments: ["Dark Piano", "Brass", "Organ", "Bass", "Percussion"], melodyDensity: 0.39, noteDensity: 0.37, phraseLength: 2, motifRepetition: 0.84, syncopation: 0.74, rhythmicComplexity: 0.7, chordComplexity: 0.27, register: "mid", octaveUsage: "low-mid with emphatic doubles", tensionAndRelease: "stops and drops before forceful returns", emotionalCharacteristics: ["aggressive", "commanding", "focused"], energy: 0.91, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "outro"], productionCharacteristics: ["hard drums", "assertive bass", "stark arrangement", "rhythmic vocal space"], referencePackWeights: { "Dancehall & Pop Dancehall": 0.95, "Dark Piano": 0.55 }, songs: [song("bounty-killer", "Look Into My Eyes", 1997, "Dancehall", "Hardcore Dancehall", ["minor", "anthemic", "forceful"]), song("bounty-killer", "Poor People Fed Up", 1998, "Dancehall", "Conscious Dancehall", ["stark", "conscious", "repetitive"]), song("bounty-killer", "Fed Up", 1996, "Dancehall", "Hardcore Dancehall", ["aggressive", "syncopated", "chant"]), song("bounty-killer", "Down In The Gully", 1996, "Dancehall", "Hardcore Dancehall", ["dark", "commanding", "bass-led"]), song("bounty-killer", "Dead This Time", 2002, "Dancehall", "Hardcore Dancehall", ["dramatic", "staccato", "high energy"]) ] }),
  artist({ artistId: "masicka", artistName: "Masicka", aliases: ["masicka"], country: "Jamaica", primaryGenres: ["Modern Trap Dancehall"], secondaryGenres: ["Dancehall", "R&B"], subgenres: ["Melodic Trap Dancehall", "Conscious Trap Dancehall"], era: "2010s-present", tempo: { min: 92, max: 108, preferred: 100 }, keyTendencies: ["minor", "minor 7 color"], scaleTendencies: ["natural minor", "dorian", "minor pentatonic"], harmonicCharacteristics: ["emotional minor cycles", "subtle extensions"], melodicCharacteristics: ["melodic rap phrasing", "hook development", "descending contours"], rhythmicCharacteristics: ["syncopated pockets", "triplet and straight contrast"], bassCharacteristics: ["808 support", "melodic low-end answers"], instrumentPreferences: ["guitar", "dark piano", "pad", "808", "bell"], commonInstruments: ["Guitar", "Dark Piano", "Pad", "808", "Bell"], melodyDensity: 0.46, noteDensity: 0.43, phraseLength: 4, motifRepetition: 0.75, syncopation: 0.67, rhythmicComplexity: 0.68, chordComplexity: 0.5, register: "mid", octaveUsage: "controlled wide range with hook lift", tensionAndRelease: "melodic tension resolved by hook cadence", emotionalCharacteristics: ["reflective", "dark", "ambitious"], energy: 0.74, songStructureTendencies: ["intro", "verse", "pre-hook", "hook", "verse", "hook"], productionCharacteristics: ["wide guitars", "emotional keys", "deep 808", "layered vocal space"], referencePackWeights: { "Modern Trap Dancehall": 0.9, "Emotional Guitar MIDI": 0.8, "Trap Emotional Piano": 0.65 }, songs: [song("masicka", "Moments", 2021, "Modern Trap Dancehall", "Melodic Trap Dancehall", ["reflective", "minor", "melodic hook"]), song("masicka", "Pieces", 2022, "Dancehall", "Conscious Dancehall", ["emotional", "guitar color", "vocal space"]), song("masicka", "Reverse", 2023, "Modern Trap Dancehall", "Melodic Trap Dancehall", ["dark", "808", "developing motif"]), song("masicka", "Yes Yes", 2021, "Dancehall", "Modern Dancehall", ["rhythmic", "catchy", "syncopated"]), song("masicka", "Pain", 2018, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["minor", "sparse", "melancholic"]) ] }),
  artist({ artistId: "teejay", artistName: "Teejay", aliases: ["teejay", "uptop boss"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Modern Trap Dancehall", "Afrobeats"], subgenres: ["Melodic Dancehall", "Pop Dancehall"], era: "2010s-present", tempo: { min: 92, max: 110, preferred: 101 }, keyTendencies: ["minor", "major", "modal"], scaleTendencies: ["natural minor", "major pentatonic", "mixolydian"], harmonicCharacteristics: ["simple warm loops", "clear hook harmony"], melodicCharacteristics: ["melodic chant hooks", "repeated vocal motifs"], rhythmicCharacteristics: ["bouncy dembow", "off-beat responses"], bassCharacteristics: ["round bass groove", "punctuated roots"], instrumentPreferences: ["guitar", "piano", "pluck", "percussion"], commonInstruments: ["Guitar", "Piano", "Pluck", "Bass", "Percussion"], melodyDensity: 0.52, noteDensity: 0.48, phraseLength: 2, motifRepetition: 0.81, syncopation: 0.7, rhythmicComplexity: 0.65, chordComplexity: 0.35, register: "mid", octaveUsage: "hook octave support", tensionAndRelease: "short repeated buildup into chorus", emotionalCharacteristics: ["warm", "confident", "uplifting"], energy: 0.8, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "outro"], productionCharacteristics: ["warm guitar", "clean rhythm", "round bass", "hook-forward mix"], referencePackWeights: { "Dancehall & Pop Dancehall": 0.9, "Afrobeat Guitar": 0.65, "Modern Trap Dancehall": 0.55 }, songs: [song("teejay", "Drift", 2023, "Dancehall", "Melodic Dancehall", ["bouncy", "melodic", "guitar-led"]), song("teejay", "People", 2022, "Dancehall", "Conscious Dancehall", ["warm", "reflective", "vocal-friendly"]), song("teejay", "I Want You", 2021, "Dancehall", "Pop Dancehall", ["romantic", "catchy", "syncopated"]), song("teejay", "From Rags", 2023, "Dancehall", "Conscious Dancehall", ["anthemic", "steady groove", "minor color"]), song("teejay", "Escobar", 2020, "Dancehall", "Modern Dancehall", ["assertive", "punchy", "repetitive"]) ] }),
  artist({ artistId: "rajahwild", artistName: "Rajahwild", aliases: ["rajahwild"], country: "Jamaica", primaryGenres: ["Modern Trap Dancehall"], secondaryGenres: ["Dancehall", "Afrobeats"], subgenres: ["Energetic Trap Dancehall"], era: "2020s", tempo: { min: 96, max: 114, preferred: 105 }, keyTendencies: ["minor", "bright minor"], scaleTendencies: ["minor pentatonic", "natural minor"], harmonicCharacteristics: ["minimal punchy loops", "quick turnarounds"], melodicCharacteristics: ["energetic repeated hooks", "short staccato cells"], rhythmicCharacteristics: ["fast syncopation", "skippy bounce", "off-beat accents"], bassCharacteristics: ["punchy 808", "short low-end responses"], instrumentPreferences: ["piano", "bell", "pluck", "808"], commonInstruments: ["Piano", "Bell", "Pluck", "808", "Percussion"], melodyDensity: 0.5, noteDensity: 0.49, phraseLength: 2, motifRepetition: 0.84, syncopation: 0.79, rhythmicComplexity: 0.78, chordComplexity: 0.3, register: "mid", octaveUsage: "high hook accents", tensionAndRelease: "rapid anticipation and dropouts", emotionalCharacteristics: ["energetic", "playful", "confident"], energy: 0.93, songStructureTendencies: ["short intro", "hook", "verse", "hook", "outro"], productionCharacteristics: ["bright attack", "punchy drums", "tight bass", "minimal arrangement"], referencePackWeights: { "Modern Trap Dancehall": 1, "Dancehall & Pop Dancehall": 0.7, "Trap 808 MIDI": 0.6 }, songs: [song("rajahwild", "Man Ah Bad", 2023, "Modern Trap Dancehall", "Energetic Trap Dancehall", ["high energy", "punchy", "short hook"]), song("rajahwild", "Sail Away", 2023, "Dancehall", "Modern Dancehall", ["bouncy", "syncopated", "melodic"]), song("rajahwild", "Wild Out", 2024, "Modern Trap Dancehall", "Energetic Trap Dancehall", ["urgent", "808", "repetitive"]), song("rajahwild", "Dweet", 2022, "Dancehall", "Modern Dancehall", ["percussive", "club", "off-beat"]), song("rajahwild", "Rich", 2024, "Modern Trap Dancehall", "Energetic Trap Dancehall", ["confident", "minimal", "piano-led"]) ] }),
  artist({ artistId: "teebone", artistName: "Teebone", aliases: ["teebone", "tee bone"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Modern Trap Dancehall", "Reggae"], subgenres: ["Street Dancehall"], era: "2010s-present", tempo: { min: 92, max: 108, preferred: 100 }, keyTendencies: ["minor", "modal"], scaleTendencies: ["natural minor", "minor pentatonic"], harmonicCharacteristics: ["sparse loops", "dark tonal anchors"], melodicCharacteristics: ["rhythmic street motifs", "short repeated phrases"], rhythmicCharacteristics: ["syncopated bounce", "staccato gaps"], bassCharacteristics: ["deep roots", "short syncopated responses"], instrumentPreferences: ["dark piano", "guitar", "bell", "bass"], commonInstruments: ["Dark Piano", "Guitar", "Bell", "Bass", "Percussion"], melodyDensity: 0.39, noteDensity: 0.37, phraseLength: 2, motifRepetition: 0.8, syncopation: 0.71, rhythmicComplexity: 0.67, chordComplexity: 0.3, register: "mid", octaveUsage: "stable mid with low response", tensionAndRelease: "space before accented returns", emotionalCharacteristics: ["street", "dark", "focused"], energy: 0.78, songStructureTendencies: ["intro", "hook", "verse", "hook", "outro"], productionCharacteristics: ["sparse drums", "dark melodic anchor", "deep bass", "tight arrangement"], referencePackWeights: { "Dancehall & Pop Dancehall": 0.8, "Modern Trap Dancehall": 0.7, "Dark Piano": 0.55 }, songs: [song("teebone", "Money", 2019, "Dancehall", "Street Dancehall", ["dark", "sparse", "bass-led"]), song("teebone", "Gully", 2020, "Dancehall", "Street Dancehall", ["syncopated", "minor", "repetitive"]), song("teebone", "Badness", 2018, "Dancehall", "Street Dancehall", ["staccato", "hard pocket", "short motif"]), song("teebone", "Pressure", 2021, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["moody", "808", "vocal space"]), song("teebone", "Top Shotta", 2020, "Dancehall", "Street Dancehall", ["assertive", "percussive", "club groove"]) ] }),
  artist({ artistId: "jamal", artistName: "Jamal", aliases: ["jamal"], country: "Jamaica", primaryGenres: ["Modern Trap Dancehall"], secondaryGenres: ["Dancehall", "R&B"], subgenres: ["Emotional Trap Dancehall"], era: "2020s", tempo: { min: 92, max: 108, preferred: 100 }, keyTendencies: ["minor", "minor 7 color"], scaleTendencies: ["natural minor", "dorian"], harmonicCharacteristics: ["spacious minor harmony", "soft suspended color"], melodicCharacteristics: ["emotional piano motifs", "vocal-friendly 4-bar phrases"], rhythmicCharacteristics: ["laid-back bounce", "selective off-beat notes"], bassCharacteristics: ["sparse 808", "held roots under gaps"], instrumentPreferences: ["emotional piano", "guitar", "pad", "bell"], commonInstruments: ["Emotional Piano", "Guitar", "Pad", "Bell", "808"], melodyDensity: 0.38, noteDensity: 0.36, phraseLength: 4, motifRepetition: 0.78, syncopation: 0.58, rhythmicComplexity: 0.55, chordComplexity: 0.52, register: "mid", octaveUsage: "high answer notes at phrase endings", tensionAndRelease: "held tensions resolving late", emotionalCharacteristics: ["emotional", "reflective", "intimate"], energy: 0.6, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "outro"], productionCharacteristics: ["soft keys", "wide atmosphere", "restrained bass", "vocal space"], referencePackWeights: { "Emotional Dancehall MIDI": 0.95, "Trap Emotional Piano": 0.8, "Emotional Guitar MIDI": 0.7 }, songs: [song("jamal", "Emotional", 2023, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["emotional", "piano-led", "sparse"]), song("jamal", "No Love", 2022, "Dancehall", "Emotional Dancehall", ["minor", "reflective", "vocal space"]), song("jamal", "Pain", 2023, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["moody", "808", "held tones"]), song("jamal", "Letter", 2024, "Dancehall", "Emotional Dancehall", ["intimate", "guitar color", "4-bar phrasing"]), song("jamal", "Again", 2022, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["repetitive", "soft harmony", "late resolution"]) ] }),
  artist({ artistId: "vybz-kartel", artistName: "Vybz Kartel", aliases: ["vybz kartel", "kartel", "world boss"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Reggae", "Pop Dancehall"], subgenres: ["Digital Dancehall", "Modern Dancehall"], era: "2000s-present", tempo: { min: 94, max: 112, preferred: 104 }, keyTendencies: ["minor", "major", "modal"], scaleTendencies: ["natural minor", "major pentatonic", "mixolydian"], harmonicCharacteristics: ["direct loops", "strong hook tonal center"], melodicCharacteristics: ["rhythmic chant hooks", "call-and-response", "compact motifs"], rhythmicCharacteristics: ["clipped syncopation", "dembow drive", "off-beat punctuation"], bassCharacteristics: ["assertive bass", "root-led groove"], instrumentPreferences: ["keys", "bell", "bass", "percussion", "guitar"], commonInstruments: ["Keys", "Bell", "Bass", "Percussion", "Guitar"], melodyDensity: 0.47, noteDensity: 0.45, phraseLength: 2, motifRepetition: 0.87, syncopation: 0.75, rhythmicComplexity: 0.71, chordComplexity: 0.3, register: "mid", octaveUsage: "compact hook doubling", tensionAndRelease: "clipped phrase endings and quick returns", emotionalCharacteristics: ["confident", "energetic", "witty"], energy: 0.88, songStructureTendencies: ["intro", "verse", "hook", "verse", "hook", "bridge"], productionCharacteristics: ["dry drums", "bold bass", "bright punctuation", "hook-forward mix"], referencePackWeights: { "Dancehall & Pop Dancehall": 1, "Modern Trap Dancehall": 0.6 }, songs: [song("vybz-kartel", "Fever", 2009, "Dancehall", "Digital Dancehall", ["catchy", "rhythmic", "club"]), song("vybz-kartel", "Summertime", 2009, "Dancehall", "Pop Dancehall", ["warm", "melodic", "hook-led"]), song("vybz-kartel", "Clarks", 2010, "Dancehall", "Pop Dancehall", ["anthemic", "call-and-response", "bright"]), song("vybz-kartel", "Romping Shop", 2009, "Dancehall", "Pop Dancehall", ["syncopated", "repetitive", "danceable"]), song("vybz-kartel", "Whine", 2008, "Dancehall", "Digital Dancehall", ["percussive", "club", "short motif"]) ] }),
  artist({ artistId: "eddy-g-bomba", artistName: "Eddy G Bomba", aliases: ["eddy g bomba", "eddy g"], country: "Jamaica", primaryGenres: ["Dancehall"], secondaryGenres: ["Modern Trap Dancehall", "Reggae"], subgenres: ["Street Dancehall"], era: "2010s-present", tempo: { min: 92, max: 110, preferred: 101 }, keyTendencies: ["minor", "modal"], scaleTendencies: ["natural minor", "minor pentatonic"], harmonicCharacteristics: ["minimal tonal loops", "dark color tones"], melodicCharacteristics: ["street hook fragments", "rhythmic motifs"], rhythmicCharacteristics: ["syncopated bounce", "percussive rests"], bassCharacteristics: ["deep round bass", "short root accents"], instrumentPreferences: ["dark piano", "bell", "guitar", "808"], commonInstruments: ["Dark Piano", "Bell", "Guitar", "808", "Percussion"], melodyDensity: 0.4, noteDensity: 0.38, phraseLength: 2, motifRepetition: 0.8, syncopation: 0.7, rhythmicComplexity: 0.67, chordComplexity: 0.3, register: "mid", octaveUsage: "controlled mid range", tensionAndRelease: "rest-led phrase turns", emotionalCharacteristics: ["dark", "street", "focused"], energy: 0.79, songStructureTendencies: ["intro", "hook", "verse", "hook", "outro"], productionCharacteristics: ["tight drums", "dark melodic layer", "deep bass", "sparse arrangement"], referencePackWeights: { "Dancehall & Pop Dancehall": 0.8, "Modern Trap Dancehall": 0.75, "Dark Piano": 0.5 }, songs: [song("eddy-g-bomba", "Bomba", 2021, "Dancehall", "Street Dancehall", ["dark", "rhythmic", "short hook"]), song("eddy-g-bomba", "Bad", 2022, "Dancehall", "Street Dancehall", ["assertive", "syncopated", "bass-led"]), song("eddy-g-bomba", "Outside", 2023, "Modern Trap Dancehall", "Street Trap Dancehall", ["sparse", "808", "urgent"]), song("eddy-g-bomba", "Gully", 2021, "Dancehall", "Street Dancehall", ["minor", "percussive", "repetitive"]), song("eddy-g-bomba", "Pressure", 2024, "Modern Trap Dancehall", "Emotional Trap Dancehall", ["moody", "held tones", "vocal space"]) ] }),
];

const genre = (genreId: string, genreName: string, tempoRange: [number, number, number], scales: string[], rhythmCharacteristics: string[], melodyDensity: number, chordTendencies: string[], bassTendencies: string[], instrumentation: string[], phraseStructures: string[], syncopation: number, energy: number, productionCharacteristics: string[], referencePackWeights: Record<string, number>): JamaicanGenreProfile => ({ genreId, genreName, tempoRange: { min: tempoRange[0], max: tempoRange[1], preferred: tempoRange[2] }, keyTendencies: ["minor", "major", "modal"], scaleTendencies: scales, rhythmCharacteristics, melodyDensity, chordTendencies, bassTendencies, instrumentation, phraseStructures, syncopation, energy, productionCharacteristics, referencePackWeights });

export const JAMAICAN_GENRE_PROFILES: JamaicanGenreProfile[] = [
  genre("trap-dancehall", "Trap Dancehall", [92, 110, 100], ["natural minor", "minor pentatonic", "phrygian"], ["dembow bounce", "trap subdivisions", "off-beat accents"], 0.42, ["sparse minor loops", "short stabs", "suspended color"], ["syncopated 808", "root-fifth punches"], ["piano", "bell", "guitar", "808", "percussion"], ["2-bar hook", "4-bar verse"], 0.72, 0.82, ["wide 808", "dark keys", "vocal space", "tight drums"], { "Modern Trap Dancehall": 1, "Trap 808 MIDI": 0.55, "Dancehall & Pop Dancehall": 0.7 }),
  genre("modern-trap-dancehall", "Modern Trap Dancehall", [95, 112, 102], ["natural minor", "minor pentatonic", "dorian"], ["skippy dembow", "hi-hat support", "anticipation"], 0.43, ["minimal loops", "minor 7 color", "rhythmic stabs"], ["punchy 808", "sliding phrase turns"], ["dark piano", "bright piano", "bell", "guitar", "808"], ["2-bar hook", "4-bar development"], 0.76, 0.86, ["wide low end", "sparse aggressive bounce", "bright hook punctuation"], { "Modern Trap Dancehall": 1, "Trap 808 MIDI": 0.7, "Dark Piano": 0.55 }),
  genre("dancehall", "Dancehall", [90, 110, 100], ["major", "mixolydian", "natural minor"], ["dembow", "off-beat guitar", "syncopated stabs"], 0.5, ["direct loops", "bright chord punches"], ["round syncopated bass", "root movement"], ["guitar", "keys", "bass", "percussion"], ["2-bar hook", "4-bar verse", "call-and-response"], 0.75, 0.78, ["dry percussion", "vocal-forward space", "clean bass pocket"], { "Dancehall & Pop Dancehall": 1, "Afrobeat Guitar": 0.55 }),
  genre("pop-dancehall", "Pop Dancehall", [94, 114, 104], ["major", "major pentatonic", "mixolydian"], ["clean dembow", "bright off-beats", "hook accents"], 0.56, ["simple pop loops", "clear cadences"], ["round bass", "hook-ending accents"], ["guitar", "piano", "pluck", "bell", "percussion"], ["4-bar verse", "8-bar chorus", "pre-hook"], 0.65, 0.8, ["bright top line", "polished drums", "wide but uncluttered mix"], { "Dancehall & Pop Dancehall": 1, "Afrobeat Chords": 0.45 }),
  genre("emotional-dancehall", "Emotional Dancehall", [88, 106, 98], ["natural minor", "dorian", "minor pentatonic"], ["laid-back dembow", "selective syncopation", "space"], 0.38, ["spacious minor loops", "7th and suspended color"], ["sparse 808", "held root tones"], ["emotional piano", "guitar", "pad", "bell", "808"], ["4-bar motif", "8-bar hook", "late resolution"], 0.56, 0.6, ["wide atmosphere", "restrained drums", "vocal space", "soft keys"], { "Emotional Dancehall MIDI": 1, "Trap Emotional Piano": 0.8, "Emotional Guitar MIDI": 0.75 }),
  genre("afrobeats", "Afrobeats", [95, 115, 105], ["major", "major pentatonic", "mixolydian"], ["rolling percussion", "interlocking syncopation", "guitar off-beats"], 0.55, ["warm repeating cycles", "gentle extensions"], ["melodic bass", "elastic syncopation"], ["guitar", "pluck", "keys", "bass", "percussion"], ["4-bar motif", "8-bar chorus", "call-and-response"], 0.67, 0.76, ["warm guitar", "layered percussion", "organic groove", "open arrangement"], { "Afrobeat Guitar": 1, "Afro Acoustic MIDI": 0.8, "Afrobeat Chords": 0.7 }),
  genre("afrobeat", "Afrobeat", [95, 115, 105], ["major", "mixolydian", "dorian"], ["polyrhythmic percussion", "repeating guitar", "off-beat accents"], 0.5, ["cyclic harmony", "modal vamp"], ["repeating bass ostinato", "syncopated movement"], ["guitar", "organ", "brass", "bass", "percussion"], ["8-bar vamp", "call-and-response"], 0.7, 0.74, ["live-feeling groove", "interlocking parts", "arrangement density"], { "Afrobeat Guitar": 0.9, "Afrobeat Chords": 0.8, "Afro Acoustic MIDI": 0.75 }),
  genre("rnb", "R&B", [65, 95, 80], ["natural minor", "dorian", "major"], ["laid-back pocket", "triplet ornament", "behind-the-beat feel"], 0.48, ["7ths", "9ths", "smooth voice leading"], ["melodic sub", "syncopated roots"], ["piano", "electric piano", "pad", "bass", "guitar"], ["4-bar motif", "8-bar chorus", "bridge"], 0.48, 0.58, ["soft transients", "rich harmony", "space and warmth"], { RNB: 1, "Emotional Guitar MIDI": 0.35 }),
  genre("trap", "Trap", [130, 155, 145], ["natural minor", "harmonic minor", "phrygian"], ["hi-hat subdivisions", "triplets", "syncopated 808"], 0.4, ["minor loops", "suspended color", "short stabs"], ["808 slides", "root and fifth punches"], ["dark piano", "bell", "pad", "808", "pluck"], ["2-bar hook", "4-bar verse"], 0.7, 0.84, ["wide 808", "dark melodic anchor", "sparse pockets"], { "Dark Trap MIDI": 0.85, "Trap 808 MIDI": 1, "Dark Piano": 0.45 }),
  genre("dark-trap", "Dark Trap", [130, 150, 142], ["natural minor", "phrygian", "harmonic minor"], ["stark gaps", "triplet fills", "heavy accents"], 0.34, ["minor ostinato", "drone", "chromatic tension"], ["deep 808", "long slides", "dropouts"], ["dark piano", "bell", "pad", "808"], ["2-bar motif", "4-bar tension"], 0.68, 0.88, ["ominous keys", "sub-heavy low end", "dramatic space"], { "Dark Trap MIDI": 1, "Dark Piano": 0.85, "Trap 808 MIDI": 0.8 }),
  genre("drill", "Drill", [135, 150, 142], ["natural minor", "phrygian", "harmonic minor"], ["sliding bass", "staccato piano", "triplet hat cells"], 0.36, ["dark minor loops", "suspended tension"], ["sliding 808", "syncopated low end"], ["drill piano", "strings", "808", "bell"], ["2-bar motif", "4-bar verse"], 0.73, 0.9, ["sliding 808", "staccato attacks", "dark sparse space"], { "Drill Piano MIDI": 1, "Trap 808 MIDI": 0.9, "Dark Trap MIDI": 0.7 }),
  genre("reggae", "Reggae", [70, 90, 80], ["major", "mixolydian", "natural minor"], ["one-drop", "off-beat skank", "laid-back pulse"], 0.42, ["simple cyclic harmony", "organ stabs"], ["melodic bass", "syncopated one-drop support"], ["guitar", "organ", "bass", "percussion"], ["4-bar vamp", "8-bar chorus"], 0.62, 0.6, ["warm low end", "off-beat guitar", "organic dynamics"], { "Dancehall & Pop Dancehall": 0.35, "Afro Acoustic MIDI": 0.3 }),
];

function normalize(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
function unique(values: string[]) { return [...new Set(values.filter(Boolean))]; }

export function detectJamaicanArtists(prompt: string) {
  const text = normalize(prompt);
  return JAMAICAN_ARTIST_PROFILES.filter((profile) => profile.aliases.some((alias) => text.includes(normalize(alias)) || text.replace(/ /g, "").includes(normalize(alias).replace(/ /g, ""))));
}

export function detectJamaicanGenre(prompt: string) {
  const text = normalize(prompt);
  return JAMAICAN_GENRE_PROFILES.slice().sort((left, right) => right.genreName.length - left.genreName.length).find((profile) => text.includes(normalize(profile.genreName)))
    ?? (text.includes("trap dancehall") || text.includes("dancehall trap") ? JAMAICAN_GENRE_PROFILES[0] : null);
}

function blendArtists(profiles: JamaicanArtistProfile[]): JamaicanArtistProfile | null {
  if (!profiles.length) return null;
  const [first] = profiles;
  if (!first) return null;
  const average = (selector: (profile: JamaicanArtistProfile) => number) => Number((profiles.reduce((sum, profile) => sum + selector(profile), 0) / profiles.length).toFixed(3));
  const weightedMaps = (selector: (profile: JamaicanArtistProfile) => Record<string, number>) => Object.fromEntries(unique(profiles.flatMap((profile) => Object.keys(selector(profile)))).map((key) => [key, average((profile) => selector(profile)[key] ?? 0)]));
  return { ...first, artistId: profiles.map((profile) => profile.artistId).join("-x-"), artistName: profiles.map((profile) => profile.artistName).join(" x "), aliases: unique(profiles.flatMap((profile) => profile.aliases)), primaryGenres: unique(profiles.flatMap((profile) => profile.primaryGenres)), secondaryGenres: unique(profiles.flatMap((profile) => profile.secondaryGenres)), subgenres: unique(profiles.flatMap((profile) => profile.subgenres)), keyTendencies: unique(profiles.flatMap((profile) => profile.keyTendencies)), scaleTendencies: unique(profiles.flatMap((profile) => profile.scaleTendencies)), harmonicCharacteristics: unique(profiles.flatMap((profile) => profile.harmonicCharacteristics)), melodicCharacteristics: unique(profiles.flatMap((profile) => profile.melodicCharacteristics)), rhythmicCharacteristics: unique(profiles.flatMap((profile) => profile.rhythmicCharacteristics)), bassCharacteristics: unique(profiles.flatMap((profile) => profile.bassCharacteristics)), instrumentPreferences: unique(profiles.flatMap((profile) => profile.instrumentPreferences)), commonInstruments: unique(profiles.flatMap((profile) => profile.commonInstruments)), emotionalCharacteristics: unique(profiles.flatMap((profile) => profile.emotionalCharacteristics)), songStructureTendencies: unique(profiles.flatMap((profile) => profile.songStructureTendencies)), productionCharacteristics: unique(profiles.flatMap((profile) => profile.productionCharacteristics)), tempo: { min: Math.round(average((profile) => profile.tempo.min)), max: Math.round(average((profile) => profile.tempo.max)), preferred: Math.round(average((profile) => profile.tempo.preferred)) }, melodyDensity: average((profile) => profile.melodyDensity), noteDensity: average((profile) => profile.noteDensity), phraseLength: Math.round(average((profile) => profile.phraseLength)), motifRepetition: average((profile) => profile.motifRepetition), syncopation: average((profile) => profile.syncopation), rhythmicComplexity: average((profile) => profile.rhythmicComplexity), chordComplexity: average((profile) => profile.chordComplexity), energy: average((profile) => profile.energy), referencePackWeights: weightedMaps((profile) => profile.referencePackWeights), songs: [], confidenceScore: average((profile) => profile.confidenceScore) };
}

export function selectReferencePacks(profile: JamaicanArtistProfile | null, genreProfile: JamaicanGenreProfile | null, prompt: string, random = Math.random) {
  const weights = new Map<string, number>();
  for (const [pack, weight] of Object.entries(profile?.referencePackWeights ?? {})) weights.set(pack, weight);
  for (const [pack, weight] of Object.entries(genreProfile?.referencePackWeights ?? {})) weights.set(pack, (weights.get(pack) ?? 0) + weight);
  const lower = prompt.toLowerCase();
  const instrumentBoosts: Array<[RegExp, string[]]> = [[/spanish|nylon|guitar/, ["Spanish Guitar MIDI Pack", "Emotional Guitar MIDI", "Afrobeat Guitar"]], [/piano|keys/, ["Dark Piano", "Trap Emotional Piano", "Drill Piano MIDI"]], [/808|bass/, ["808 MIDI", "Trap 808 MIDI"]]];
  for (const [pattern, packs] of instrumentBoosts) if (pattern.test(lower)) packs.forEach((pack) => weights.set(pack, (weights.get(pack) ?? 0) + 0.65));
  const pool = [...weights.entries()].filter(([, weight]) => weight > 0).sort((left, right) => right[1] - left[1]);
  const selected: Array<{ pack: string; weight: number }> = [];
  const explicitPacks = instrumentBoosts.flatMap(([pattern, packs]) => pattern.test(lower) ? packs : []).filter((pack, index, values) => values.indexOf(pack) === index && weights.has(pack));
  for (const pack of explicitPacks) {
    const weight = weights.get(pack) ?? 0;
    selected.push({ pack, weight: Number(weight.toFixed(3)) });
    const index = pool.findIndex(([candidate]) => candidate === pack);
    if (index >= 0) pool.splice(index, 1);
    if (selected.length === 5) break;
  }
  while (pool.length && selected.length < 5) {
    const total = pool.reduce((sum, [, weight]) => sum + weight, 0);
    let target = random() * total;
    const index = pool.findIndex(([, weight]) => (target -= weight) <= 0);
    const [pack, weight] = pool.splice(index < 0 ? 0 : index, 1)[0]!;
    selected.push({ pack, weight: Number(weight.toFixed(3)) });
  }
  return selected;
}

export function buildJamaicanGenerationContext(prompt: string, preferences: Omit<JamaicanGenerationContext["userPreferences"], "prompt"> = {}): JamaicanGenerationContext {
  const artists = detectJamaicanArtists(prompt);
  const profile = blendArtists(artists);
  const genreProfile = detectJamaicanGenre(prompt) ?? JAMAICAN_GENRE_PROFILES.find((candidate) => profile?.primaryGenres.includes(candidate.genreName)) ?? null;
  const instrument = preferences.instrument ?? (prompt.match(/spanish|nylon|guitar|piano|keys|bell|808|bass|pluck|pad/i)?.[0] ?? undefined);
  const instrumentProfile = instrument ? { name: instrument, weight: 1 } : null;
  const { songs: _songs, ...profileWithoutSongs } = profile ?? {};
  return { artistProfile: profile ? profileWithoutSongs : null, genreProfile, instrumentProfile, userPreferences: { prompt, ...preferences }, referenceFeatures: selectReferencePacks(profile, genreProfile, prompt), generationConstraints: { originalComposition: true, noLyrics: true, noKnownSongMelody: true, explicitUserDirectionWins: true as const, influenceWeights: { artist: 0.45, genre: 0.3, instrument: 0.15, reference: 0.1 } } };
}

export function aggregateArtistStyle(songs: AnalyzedSongStyle[]): AggregatedArtistStyle {
  const valid = songs.filter((song) => song.confidence >= 0 && (song.tempo !== null || song.melodyDensity !== undefined || song.harmonicDensity !== undefined || song.rhythmicDensity !== undefined));
  const average = (selector: (song: AnalyzedSongStyle) => number | null | undefined) => {
    const values = valid.map(selector).filter((value): value is number => typeof value === "number" && Number.isFinite(value));
    return values.length ? Number((values.reduce((sum, value) => sum + value, 0) / values.length).toFixed(3)) : null;
  };
  const tempos = valid.map((song) => song.tempo).filter((tempo): tempo is number => typeof tempo === "number" && Number.isFinite(tempo));
  const frequencies: Record<string, number> = {};
  const instrumentCounts: Record<string, number> = {};
  for (const song of valid) {
    for (const instrument of song.instruments ?? []) instrumentCounts[instrument] = (instrumentCounts[instrument] ?? 0) + 1;
    if (song.register) frequencies[song.register] = (frequencies[song.register] ?? 0) + 1;
  }
  const instrumentWeights = Object.fromEntries(Object.entries(instrumentCounts).map(([instrument, count]) => [instrument, Number((count / Math.max(1, valid.length)).toFixed(3))]));
  return {
    songCount: valid.length,
    tempo: { min: tempos.length ? Math.min(...tempos) : null, max: tempos.length ? Math.max(...tempos) : null, preferred: average((song) => song.tempo) },
    averages: { melodyDensity: average((song) => song.melodyDensity), harmonicDensity: average((song) => song.harmonicDensity), rhythmicDensity: average((song) => song.rhythmicDensity), syncopation: average((song) => song.syncopation), motifRepetition: average((song) => song.motifRepetition), phraseLength: average((song) => song.phraseLength), energy: average((song) => song.energy) },
    frequencies,
    instrumentWeights,
    confidence: average((song) => song.confidence) ?? 0,
  };
}