import type { ChordProgression, GenreKnowledge, InstrumentKnowledge, KeyKnowledge, MoodKnowledge, PluginRecommendationKnowledge, ScaleKnowledge, SongStructureKnowledge, TempoRange, TimeSignatureKnowledge } from "./types.js";

export const GENRES: GenreKnowledge[] = [
  { name: "Trap", description: "Dark, syncopated hip-hop production with 808s, sparse melodic hooks, and half-time feel.", bpmRange: [140, 150], defaultBpm: 145, commonKeys: ["F Minor", "A Minor", "C Minor"], tonalityPreference: "Minor", recommendedScales: ["Natural Minor", "Harmonic Minor", "Phrygian"], typicalStructure: "Trap Hook/Verse", chordProgressions: [["i", "VI", "VII"], ["i", "iv", "V"], ["i", "VII", "VI", "VII"]], energyLevel: "Medium", moodTags: ["Dark", "Aggressive", "Emotional"], instrumentRecommendations: ["Bell", "Piano", "808", "Pad"], pluginCategories: ["Bell Pluck", "Deep 808", "Dark Pad"], difficulty: "Intermediate" },
  { name: "Drill", description: "Tense minor-key rap production with sliding 808s, sparse motifs, and hard rhythmic pockets.", bpmRange: [138, 144], defaultBpm: 140, commonKeys: ["F Minor", "G Minor", "C Minor"], tonalityPreference: "Minor", recommendedScales: ["Natural Minor", "Harmonic Minor"], typicalStructure: "Drill Hook/Verse", chordProgressions: [["i", "VI", "VII"], ["i", "v", "VI"]], energyLevel: "High", moodTags: ["Dark", "Aggressive", "Mysterious"], instrumentRecommendations: ["Piano", "Strings", "808", "Choir"], pluginCategories: ["Dark Piano", "String Stab", "Deep 808"], difficulty: "Advanced" },
  { name: "Hip Hop", description: "Beat-driven rap production with loops, drums, bass, and sample-inspired harmony.", bpmRange: [85, 100], defaultBpm: 92, commonKeys: ["A Minor", "C Minor", "D Minor"], tonalityPreference: "Mixed", recommendedScales: ["Natural Minor", "Pentatonic Minor", "Blues Scale"], typicalStructure: "Verse/Hook", chordProgressions: [["i", "VII", "VI"], ["I", "vi", "IV", "V"]], energyLevel: "Medium", moodTags: ["Confident", "Relaxed"], instrumentRecommendations: ["Rhodes", "Bass", "Percussion"], pluginCategories: ["Warm Keys", "Analog Bass"], difficulty: "Intermediate" },
  { name: "Boom Bap", description: "Classic sample-forward hip-hop with dusty drums, jazz harmony, and compact loops.", bpmRange: [82, 94], defaultBpm: 88, commonKeys: ["D Minor", "E Minor"], tonalityPreference: "Mixed", recommendedScales: ["Dorian", "Blues Scale", "Pentatonic Minor"], typicalStructure: "Loop Verse/Hook", chordProgressions: [["ii", "V", "i"], ["i", "iv"]], energyLevel: "Medium", moodTags: ["Relaxed", "Confident"], instrumentRecommendations: ["Rhodes", "Brass", "Bass"], pluginCategories: ["Dusty Keys", "Vinyl Texture"], difficulty: "Intermediate" },
  { name: "LoFi", description: "Warm, relaxed, humanized music with soft drums, jazz color, and nostalgic texture.", bpmRange: [65, 85], defaultBpm: 74, commonKeys: ["C Major", "A Minor", "F Major"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Dorian", "Pentatonic Major"], typicalStructure: "Loop", chordProgressions: [["ii", "V", "I"], ["I", "vi", "ii", "V"]], energyLevel: "Low", moodTags: ["Relaxed", "Melancholy", "Dreamy"], instrumentRecommendations: ["Rhodes", "Soft Piano", "Pad"], pluginCategories: ["Warm Piano", "Tape Texture"], difficulty: "Beginner" },
  { name: "House", description: "Four-on-the-floor dance music with steady pulse, piano or synth hooks, and club structure.", bpmRange: [120, 128], defaultBpm: 126, commonKeys: ["A Minor", "C Minor", "F Minor"], tonalityPreference: "Mixed", recommendedScales: ["Minor", "Dorian", "Major"], typicalStructure: "Club Arrangement", chordProgressions: [["i", "VI", "III", "VII"], ["I", "V", "vi", "IV"]], energyLevel: "High", moodTags: ["Energetic", "Happy"], instrumentRecommendations: ["Piano", "Synth Bass", "Pad"], pluginCategories: ["House Piano", "Deep Bass"], difficulty: "Intermediate" },
  { name: "EDM", description: "High-energy electronic production built around hooks, drops, risers, and wide synth layers.", bpmRange: [126, 130], defaultBpm: 128, commonKeys: ["F Minor", "G Minor", "A Minor"], tonalityPreference: "Mixed", recommendedScales: ["Natural Minor", "Major"], typicalStructure: "Build/Drop", chordProgressions: [["i", "VI", "III", "VII"], ["vi", "IV", "I", "V"]], energyLevel: "High", moodTags: ["Energetic", "Epic"], instrumentRecommendations: ["Lead", "Pad", "Bass"], pluginCategories: ["Wide Lead", "Festival Pluck"], difficulty: "Advanced" },
  { name: "Tech House", description: "Minimal club-focused house with tight basslines, short hooks, and percussion-driven grooves.", bpmRange: [124, 128], defaultBpm: 126, commonKeys: ["A Minor", "F Minor"], tonalityPreference: "Minor", recommendedScales: ["Dorian", "Natural Minor"], typicalStructure: "Club Arrangement", chordProgressions: [["i"], ["i", "VII"]], energyLevel: "High", moodTags: ["Energetic", "Confident"], instrumentRecommendations: ["Bass", "Percussion", "Synth"], pluginCategories: ["Deep Bass", "Percussion FX"], difficulty: "Intermediate" },
  { name: "Techno", description: "Hypnotic electronic music focused on repetition, sound design, and evolving rhythmic energy.", bpmRange: [126, 135], defaultBpm: 130, commonKeys: ["F Minor", "C Minor"], tonalityPreference: "Minor", recommendedScales: ["Phrygian", "Natural Minor"], typicalStructure: "Evolving Club Arrangement", chordProgressions: [["i"], ["i", "bII"]], energyLevel: "High", moodTags: ["Dark", "Mysterious"], instrumentRecommendations: ["Synth", "Bass", "FX"], pluginCategories: ["Dark Pad", "Analog Bass"], difficulty: "Advanced" },
  { name: "Future Bass", description: "Bright electronic music with lush chords, sidechained synth stacks, and emotional drops.", bpmRange: [140, 160], defaultBpm: 150, commonKeys: ["D Major", "A Major", "F# Minor"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Pentatonic Major"], typicalStructure: "Build/Drop", chordProgressions: [["I", "V", "vi", "IV"], ["vi", "IV", "I", "V"]], energyLevel: "High", moodTags: ["Hopeful", "Emotional", "Epic"], instrumentRecommendations: ["Pad", "Lead", "Synth"], pluginCategories: ["Wide Lead", "Bright Pluck"], difficulty: "Advanced" },
  { name: "Dubstep", description: "Heavy bass music with halftime drums, aggressive sound design, and drop-focused structure.", bpmRange: [140, 150], defaultBpm: 145, commonKeys: ["F Minor", "C Minor"], tonalityPreference: "Minor", recommendedScales: ["Phrygian", "Natural Minor"], typicalStructure: "Build/Drop", chordProgressions: [["i"], ["i", "VI"]], energyLevel: "Extreme", moodTags: ["Aggressive", "Dark"], instrumentRecommendations: ["Bass", "Lead", "FX"], pluginCategories: ["Deep 808", "Wide Lead"], difficulty: "Expert" },
  { name: "Dancehall", description: "Rhythmic Caribbean production with syncopated grooves and bright melodic hooks.", bpmRange: [90, 110], defaultBpm: 100, commonKeys: ["C Major", "A Minor"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Mixolydian"], typicalStructure: "Verse/Hook", chordProgressions: [["i", "VII", "VI"], ["I", "V", "vi", "IV"]], energyLevel: "Medium", moodTags: ["Energetic", "Happy"], instrumentRecommendations: ["Guitar", "Pluck", "Bass"], pluginCategories: ["Bell Pluck", "Warm Keys"], difficulty: "Intermediate" },
  { name: "Afrobeats", description: "Groove-first African pop music with syncopated percussion, guitars, plucks, and warm harmony.", bpmRange: [95, 115], defaultBpm: 102, commonKeys: ["D Major", "A Minor", "F Major"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Pentatonic Major", "Mixolydian"], typicalStructure: "Verse/Hook", chordProgressions: [["I", "V", "vi", "IV"], ["vi", "IV", "I", "V"]], energyLevel: "Medium", moodTags: ["Happy", "Relaxed", "Energetic"], instrumentRecommendations: ["Guitar", "Bell", "Bass", "Percussion"], pluginCategories: ["Bell Pluck", "Warm Guitar"], difficulty: "Intermediate" },
  { name: "Reggae", description: "Laid-back offbeat music with warm bass, organ skanks, and relaxed major/minor harmony.", bpmRange: [70, 90], defaultBpm: 78, commonKeys: ["C Major", "G Major", "A Minor"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Mixolydian"], typicalStructure: "Verse/Chorus", chordProgressions: [["I", "V", "vi", "IV"], ["i", "VII"]], energyLevel: "Low", moodTags: ["Relaxed", "Hopeful"], instrumentRecommendations: ["Guitar", "Keys", "Bass"], pluginCategories: ["Warm Keys", "Analog Bass"], difficulty: "Beginner" },
  { name: "R&B", description: "Smooth vocal-forward music with rich chords, warm keys, bass, and emotional movement.", bpmRange: [65, 90], defaultBpm: 75, commonKeys: ["A Minor", "C# Minor", "F Major"], tonalityPreference: "Mixed", recommendedScales: ["Natural Minor", "Dorian", "Major"], typicalStructure: "Verse/Chorus/Bridge", chordProgressions: [["ii", "V", "I"], ["vi", "IV", "I", "V"]], energyLevel: "Low", moodTags: ["Romantic", "Emotional", "Relaxed"], instrumentRecommendations: ["Keys", "Pad", "Bass"], pluginCategories: ["Warm Piano", "Dark Pad"], difficulty: "Advanced" },
  { name: "Soul", description: "Expressive music rooted in gospel, blues, warm harmony, live-feel rhythm, and vocal emotion.", bpmRange: [70, 95], defaultBpm: 82, commonKeys: ["F Major", "C Major", "D Minor"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Blues Scale", "Dorian"], typicalStructure: "Verse/Chorus/Bridge", chordProgressions: [["I", "vi", "IV", "V"], ["ii", "V", "I"]], energyLevel: "Medium", moodTags: ["Emotional", "Hopeful"], instrumentRecommendations: ["Keys", "Choir", "Bass"], pluginCategories: ["Warm Piano", "Soft Choir"], difficulty: "Advanced" },
  { name: "Pop", description: "Hook-focused music with clear structure, accessible harmony, and strong melodic identity.", bpmRange: [95, 125], defaultBpm: 110, commonKeys: ["C Major", "G Major", "A Minor"], tonalityPreference: "Major", recommendedScales: ["Major", "Pentatonic Major"], typicalStructure: "Verse/Chorus/Bridge", chordProgressions: [["I", "V", "vi", "IV"], ["vi", "IV", "I", "V"]], energyLevel: "Medium", moodTags: ["Happy", "Hopeful", "Energetic"], instrumentRecommendations: ["Piano", "Guitar", "Synth"], pluginCategories: ["Warm Piano", "Wide Lead"], difficulty: "Beginner" },
  { name: "Rock", description: "Guitar-driven music with strong riffs, direct harmony, live drums, and dynamic sections.", bpmRange: [100, 140], defaultBpm: 120, commonKeys: ["E Minor", "A Minor", "G Major"], tonalityPreference: "Mixed", recommendedScales: ["Pentatonic Minor", "Blues Scale", "Natural Minor"], typicalStructure: "Verse/Chorus/Bridge", chordProgressions: [["i", "VI", "VII"], ["I", "IV", "V"]], energyLevel: "High", moodTags: ["Aggressive", "Confident"], instrumentRecommendations: ["Guitar", "Bass", "Percussion"], pluginCategories: ["Warm Guitar", "Analog Bass"], difficulty: "Intermediate" },
  { name: "Jazz", description: "Harmony-rich music with extended chords, swing or straight grooves, and improvisational color.", bpmRange: [90, 140], defaultBpm: 110, commonKeys: ["C Major", "F Major", "D Minor"], tonalityPreference: "Mixed", recommendedScales: ["Dorian", "Mixolydian", "Blues Scale"], typicalStructure: "Head/Solos", chordProgressions: [["ii", "V", "I"], ["I", "vi", "ii", "V"]], energyLevel: "Medium", moodTags: ["Relaxed", "Romantic"], instrumentRecommendations: ["Piano", "Brass", "Bass"], pluginCategories: ["Warm Piano", "Soft Brass"], difficulty: "Expert" },
  { name: "Blues", description: "Expressive music based on blues scale, dominant harmony, call-and-response phrasing, and groove.", bpmRange: [70, 120], defaultBpm: 90, commonKeys: ["E Minor", "A Minor", "G Major"], tonalityPreference: "Mixed", recommendedScales: ["Blues Scale", "Pentatonic Minor"], typicalStructure: "12 Bar Blues", chordProgressions: [["I", "IV", "V"], ["i", "iv", "V"]], energyLevel: "Medium", moodTags: ["Melancholy", "Confident"], instrumentRecommendations: ["Guitar", "Piano", "Bass"], pluginCategories: ["Warm Guitar", "Warm Piano"], difficulty: "Intermediate" },
  { name: "Country", description: "Story-driven music with guitars, simple harmony, warm melodies, and clear verse/chorus sections.", bpmRange: [85, 120], defaultBpm: 100, commonKeys: ["G Major", "D Major", "A Major"], tonalityPreference: "Major", recommendedScales: ["Major", "Pentatonic Major"], typicalStructure: "Verse/Chorus/Bridge", chordProgressions: [["I", "V", "vi", "IV"], ["I", "IV", "V"]], energyLevel: "Medium", moodTags: ["Hopeful", "Relaxed"], instrumentRecommendations: ["Guitar", "Piano", "Strings"], pluginCategories: ["Warm Guitar", "Warm Piano"], difficulty: "Beginner" },
  { name: "Classical", description: "Formal composition rooted in orchestration, voice leading, motifs, and functional harmony.", bpmRange: [70, 120], defaultBpm: 90, commonKeys: ["C Major", "A Minor", "D Minor"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Natural Minor", "Harmonic Minor"], typicalStructure: "Theme/Development", chordProgressions: [["I", "IV", "V", "I"], ["i", "iv", "V", "i"]], energyLevel: "Medium", moodTags: ["Epic", "Emotional"], instrumentRecommendations: ["Piano", "Strings", "Woodwinds"], pluginCategories: ["Warm Piano", "Soft Strings"], difficulty: "Expert" },
  { name: "Orchestral", description: "Large ensemble scoring with strings, brass, woodwinds, percussion, and cinematic dynamics.", bpmRange: [70, 120], defaultBpm: 92, commonKeys: ["D Minor", "F Minor", "C Major"], tonalityPreference: "Mixed", recommendedScales: ["Natural Minor", "Harmonic Minor", "Major"], typicalStructure: "Cinematic Cue", chordProgressions: [["i", "VI", "III", "VII"], ["I", "V", "vi", "IV"]], energyLevel: "High", moodTags: ["Epic", "Cinematic", "Mysterious"], instrumentRecommendations: ["Strings", "Brass", "Choir"], pluginCategories: ["Soft Choir", "Soft Strings"], difficulty: "Expert" },
  { name: "Synthwave", description: "Retro electronic music with analog synths, pulsing bass, nostalgic harmony, and 80s texture.", bpmRange: [90, 115], defaultBpm: 100, commonKeys: ["A Minor", "C Minor", "D Major"], tonalityPreference: "Mixed", recommendedScales: ["Natural Minor", "Major"], typicalStructure: "Verse/Hook", chordProgressions: [["i", "VI", "III", "VII"], ["vi", "IV", "I", "V"]], energyLevel: "Medium", moodTags: ["Dreamy", "Melancholy"], instrumentRecommendations: ["Synth", "Pad", "Bass"], pluginCategories: ["Dark Pad", "Wide Lead"], difficulty: "Intermediate" },
  { name: "Phonk", description: "Dark internet-born rap/electronic style with cowbells, distorted bass, and aggressive loops.", bpmRange: [140, 165], defaultBpm: 150, commonKeys: ["F Minor", "C Minor"], tonalityPreference: "Minor", recommendedScales: ["Phrygian", "Natural Minor"], typicalStructure: "Loop", chordProgressions: [["i"], ["i", "VII"]], energyLevel: "High", moodTags: ["Dark", "Aggressive"], instrumentRecommendations: ["Bell", "808", "FX"], pluginCategories: ["Bell Pluck", "Deep 808"], difficulty: "Intermediate" },
  { name: "Cinematic", description: "Narrative scoring style with evolving arrangement, orchestral colors, and strong emotional arc.", bpmRange: [70, 120], defaultBpm: 88, commonKeys: ["D Minor", "F Minor", "C Major"], tonalityPreference: "Mixed", recommendedScales: ["Natural Minor", "Harmonic Minor", "Lydian"], typicalStructure: "Cinematic Cue", chordProgressions: [["i", "VI", "III", "VII"], ["I", "V", "vi", "IV"]], energyLevel: "High", moodTags: ["Epic", "Mysterious", "Emotional"], instrumentRecommendations: ["Strings", "Choir", "Brass"], pluginCategories: ["Soft Choir", "Dark Pad"], difficulty: "Advanced" },
  { name: "Ambient", description: "Atmospheric texture-first music with slow harmonic motion, pads, drones, and evolving space.", bpmRange: [50, 90], defaultBpm: 70, commonKeys: ["C Major", "A Minor", "D Major"], tonalityPreference: "Modal", recommendedScales: ["Lydian", "Dorian", "Major"], typicalStructure: "Evolving Texture", chordProgressions: [["I", "V"], ["i", "VII"]], energyLevel: "Very Low", moodTags: ["Relaxed", "Dreamy", "Mysterious"], instrumentRecommendations: ["Pad", "FX", "Choir"], pluginCategories: ["Dark Pad", "Soft Choir"], difficulty: "Intermediate" },
  { name: "Latin", description: "Rhythm-rich music with syncopation, guitars, piano montunos, brass, and danceable movement.", bpmRange: [90, 120], defaultBpm: 104, commonKeys: ["C Major", "A Minor", "D Minor"], tonalityPreference: "Mixed", recommendedScales: ["Major", "Harmonic Minor", "Mixolydian"], typicalStructure: "Verse/Chorus", chordProgressions: [["i", "V", "i"], ["I", "IV", "V"]], energyLevel: "High", moodTags: ["Energetic", "Romantic"], instrumentRecommendations: ["Guitar", "Piano", "Brass"], pluginCategories: ["Warm Guitar", "Soft Brass"], difficulty: "Advanced" },
  { name: "Gospel", description: "Soulful worship-rooted music with rich chords, organ, piano, choir, and strong emotional cadence.", bpmRange: [75, 110], defaultBpm: 88, commonKeys: ["C Major", "F Major", "Bb Major"], tonalityPreference: "Major", recommendedScales: ["Major", "Mixolydian", "Blues Scale"], typicalStructure: "Verse/Chorus/Bridge", chordProgressions: [["I", "vi", "IV", "V"], ["ii", "V", "I"]], energyLevel: "Medium", moodTags: ["Hopeful", "Inspirational", "Emotional"], instrumentRecommendations: ["Piano", "Choir", "Keys"], pluginCategories: ["Warm Piano", "Soft Choir"], difficulty: "Advanced" },
];

export const TEMPO_RANGES: TempoRange[] = GENRES.map((genre) => ({ genre: genre.name, minBpm: genre.bpmRange[0], maxBpm: genre.bpmRange[1], defaultBpm: genre.defaultBpm }));

export const SCALES: ScaleKnowledge[] = [
  { name: "Natural Minor", intervals: [0, 2, 3, 5, 7, 8, 10], moodTags: ["Dark", "Sad", "Emotional"], genres: ["Trap", "Drill", "R&B", "Cinematic"], difficulty: "Beginner" },
  { name: "Harmonic Minor", intervals: [0, 2, 3, 5, 7, 8, 11], moodTags: ["Dark", "Epic", "Mysterious"], genres: ["Trap", "Classical", "Latin", "Cinematic"], difficulty: "Advanced" },
  { name: "Melodic Minor", intervals: [0, 2, 3, 5, 7, 9, 11], moodTags: ["Mysterious", "Romantic"], genres: ["Jazz", "Classical"], difficulty: "Expert" },
  { name: "Major", intervals: [0, 2, 4, 5, 7, 9, 11], moodTags: ["Happy", "Hopeful", "Inspirational"], genres: ["Pop", "Country", "Gospel", "Afrobeats"], difficulty: "Beginner" },
  { name: "Pentatonic Major", intervals: [0, 2, 4, 7, 9], moodTags: ["Happy", "Relaxed"], genres: ["Country", "Pop", "Afrobeats"], difficulty: "Beginner" },
  { name: "Pentatonic Minor", intervals: [0, 3, 5, 7, 10], moodTags: ["Confident", "Melancholy"], genres: ["Rock", "Hip Hop", "Blues"], difficulty: "Beginner" },
  { name: "Dorian", intervals: [0, 2, 3, 5, 7, 9, 10], moodTags: ["Relaxed", "Soulful"], genres: ["Jazz", "R&B", "LoFi"], difficulty: "Intermediate" },
  { name: "Mixolydian", intervals: [0, 2, 4, 5, 7, 9, 10], moodTags: ["Confident", "Hopeful"], genres: ["Gospel", "Reggae", "Latin"], difficulty: "Intermediate" },
  { name: "Phrygian", intervals: [0, 1, 3, 5, 7, 8, 10], moodTags: ["Dark", "Aggressive"], genres: ["Techno", "Phonk", "Dubstep"], difficulty: "Advanced" },
  { name: "Lydian", intervals: [0, 2, 4, 6, 7, 9, 11], moodTags: ["Dreamy", "Hopeful"], genres: ["Ambient", "Cinematic"], difficulty: "Advanced" },
  { name: "Locrian", intervals: [0, 1, 3, 5, 6, 8, 10], moodTags: ["Mysterious", "Dark"], genres: ["Cinematic", "Experimental"], difficulty: "Expert" },
  { name: "Blues Scale", intervals: [0, 3, 5, 6, 7, 10], moodTags: ["Melancholy", "Confident"], genres: ["Blues", "Jazz", "Rock"], difficulty: "Intermediate" },
  { name: "Whole Tone", intervals: [0, 2, 4, 6, 8, 10], moodTags: ["Dreamy", "Mysterious"], genres: ["Cinematic", "Jazz"], difficulty: "Expert" },
  { name: "Chromatic", intervals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], moodTags: ["Mysterious", "Aggressive"], genres: ["Classical", "Cinematic"], difficulty: "Expert" },
];

export const KEYS: KeyKnowledge[] = [
  "C Major", "G Major", "D Major", "A Major", "F Major", "Bb Major", "A Minor", "E Minor", "D Minor", "F Minor", "C Minor", "G Minor", "C# Minor", "F# Minor",
].map((name, index) => ({
  name,
  tonality: name.endsWith("Minor") ? "Minor" : "Major",
  popularity: 100 - index * 4,
  genreMatch: name.endsWith("Minor") ? ["Trap", "Drill", "R&B", "Cinematic"] : ["Pop", "Country", "Gospel", "Afrobeats"],
  moodMatch: name.endsWith("Minor") ? ["Dark", "Sad", "Emotional", "Mysterious"] : ["Happy", "Hopeful", "Inspirational", "Relaxed"],
  difficulty: index < 6 ? "Beginner" : "Intermediate",
}));

export const CHORD_PROGRESSIONS: ChordProgression[] = [
  { romanNumerals: ["i", "VI", "VII"], exampleKey: "A Minor", moodTags: ["Dark", "Emotional"], genres: ["Trap", "Drill"], energy: "Medium", complexity: "Beginner", popularity: 96 },
  { romanNumerals: ["i", "VI", "III", "VII"], exampleKey: "A Minor", moodTags: ["Epic", "Emotional"], genres: ["EDM", "Synthwave", "Cinematic"], energy: "High", complexity: "Intermediate", popularity: 94 },
  { romanNumerals: ["I", "V", "vi", "IV"], exampleKey: "C Major", moodTags: ["Happy", "Hopeful"], genres: ["Pop", "Country", "Afrobeats"], energy: "Medium", complexity: "Beginner", popularity: 99 },
  { romanNumerals: ["vi", "IV", "I", "V"], exampleKey: "A Minor", moodTags: ["Emotional", "Hopeful"], genres: ["Future Bass", "Pop", "EDM"], energy: "High", complexity: "Beginner", popularity: 95 },
  { romanNumerals: ["ii", "V", "I"], exampleKey: "C Major", moodTags: ["Relaxed", "Romantic"], genres: ["Jazz", "LoFi", "R&B"], energy: "Low", complexity: "Advanced", popularity: 90 },
  { romanNumerals: ["I", "vi", "ii", "V"], exampleKey: "C Major", moodTags: ["Romantic", "Relaxed"], genres: ["Jazz", "LoFi", "Soul"], energy: "Low", complexity: "Advanced", popularity: 86 },
  { romanNumerals: ["I", "IV", "V"], exampleKey: "G Major", moodTags: ["Happy", "Confident"], genres: ["Rock", "Country", "Blues"], energy: "Medium", complexity: "Beginner", popularity: 92 },
  { romanNumerals: ["i", "iv", "V"], exampleKey: "D Minor", moodTags: ["Dark", "Mysterious"], genres: ["Classical", "Latin", "Trap"], energy: "Medium", complexity: "Intermediate", popularity: 84 },
  { romanNumerals: ["i"], exampleKey: "F Minor", moodTags: ["Dark", "Aggressive"], genres: ["Techno", "Phonk", "Dubstep"], energy: "High", complexity: "Beginner", popularity: 75 },
  { romanNumerals: ["i", "bII"], exampleKey: "F Minor", moodTags: ["Mysterious", "Dark"], genres: ["Techno", "Cinematic"], energy: "High", complexity: "Advanced", popularity: 72 },
  { romanNumerals: ["I", "V"], exampleKey: "C Major", moodTags: ["Calm", "Dreamy"], genres: ["Ambient", "Reggae"], energy: "Very Low", complexity: "Beginner", popularity: 70 },
  { romanNumerals: ["I", "vi", "IV", "V"], exampleKey: "C Major", moodTags: ["Hopeful", "Inspirational"], genres: ["Gospel", "Soul", "Pop"], energy: "Medium", complexity: "Intermediate", popularity: 88 },
];

export const MOODS: MoodKnowledge[] = [
  { name: "Dark", suggestedKeys: ["F Minor", "C Minor"], suggestedScales: ["Natural Minor", "Phrygian"], suggestedBpm: [130, 150], suggestedChords: [["i", "VI", "VII"]], suggestedInstruments: ["Bell", "808", "Pad"] },
  { name: "Happy", suggestedKeys: ["C Major", "G Major"], suggestedScales: ["Major", "Pentatonic Major"], suggestedBpm: [95, 125], suggestedChords: [["I", "V", "vi", "IV"]], suggestedInstruments: ["Piano", "Guitar", "Bell"] },
  { name: "Sad", suggestedKeys: ["A Minor", "D Minor"], suggestedScales: ["Natural Minor"], suggestedBpm: [65, 90], suggestedChords: [["i", "VI", "VII"]], suggestedInstruments: ["Soft Piano", "Strings", "Pad"] },
  { name: "Aggressive", suggestedKeys: ["F Minor", "G Minor"], suggestedScales: ["Phrygian", "Natural Minor"], suggestedBpm: [140, 165], suggestedChords: [["i"], ["i", "bII"]], suggestedInstruments: ["808", "Brass", "Lead"] },
  { name: "Dreamy", suggestedKeys: ["D Major", "A Minor"], suggestedScales: ["Lydian", "Dorian"], suggestedBpm: [70, 105], suggestedChords: [["I", "V"], ["vi", "IV", "I", "V"]], suggestedInstruments: ["Pad", "Choir", "Synth"] },
  { name: "Epic", suggestedKeys: ["D Minor", "F Minor"], suggestedScales: ["Harmonic Minor", "Natural Minor"], suggestedBpm: [90, 130], suggestedChords: [["i", "VI", "III", "VII"]], suggestedInstruments: ["Strings", "Brass", "Choir"] },
  { name: "Relaxed", suggestedKeys: ["C Major", "A Minor"], suggestedScales: ["Dorian", "Major"], suggestedBpm: [65, 90], suggestedChords: [["ii", "V", "I"]], suggestedInstruments: ["Rhodes", "Guitar", "Pad"] },
  { name: "Romantic", suggestedKeys: ["F Major", "C# Minor"], suggestedScales: ["Major", "Dorian"], suggestedBpm: [65, 90], suggestedChords: [["ii", "V", "I"], ["vi", "IV", "I", "V"]], suggestedInstruments: ["Keys", "Pad", "Bass"] },
  { name: "Hopeful", suggestedKeys: ["G Major", "D Major"], suggestedScales: ["Major", "Lydian"], suggestedBpm: [90, 125], suggestedChords: [["I", "V", "vi", "IV"]], suggestedInstruments: ["Piano", "Guitar", "Strings"] },
  { name: "Mysterious", suggestedKeys: ["C Minor", "F Minor"], suggestedScales: ["Phrygian", "Whole Tone"], suggestedBpm: [70, 120], suggestedChords: [["i", "bII"]], suggestedInstruments: ["Pad", "Choir", "FX"] },
  { name: "Inspirational", suggestedKeys: ["C Major", "F Major"], suggestedScales: ["Major", "Mixolydian"], suggestedBpm: [80, 115], suggestedChords: [["I", "vi", "IV", "V"]], suggestedInstruments: ["Piano", "Choir", "Strings"] },
  { name: "Energetic", suggestedKeys: ["A Minor", "C Major"], suggestedScales: ["Major", "Natural Minor"], suggestedBpm: [120, 150], suggestedChords: [["i", "VI", "III", "VII"], ["I", "V", "vi", "IV"]], suggestedInstruments: ["Lead", "Bass", "Percussion"] },
  { name: "Melancholy", suggestedKeys: ["A Minor", "D Minor"], suggestedScales: ["Dorian", "Natural Minor"], suggestedBpm: [65, 95], suggestedChords: [["i", "VI", "VII"], ["ii", "V", "I"]], suggestedInstruments: ["Rhodes", "Strings", "Pad"] },
  { name: "Confident", suggestedKeys: ["E Minor", "G Major"], suggestedScales: ["Pentatonic Minor", "Mixolydian"], suggestedBpm: [85, 125], suggestedChords: [["I", "IV", "V"], ["i", "VII"]], suggestedInstruments: ["Guitar", "Brass", "Bass"] },
];

export const INSTRUMENTS: InstrumentKnowledge[] = [
  { name: "Soft Piano", category: "Piano", genres: ["LoFi", "R&B", "Classical"], moodMatch: ["Sad", "Emotional", "Romantic"], energyMatch: ["Very Low", "Low", "Medium"] },
  { name: "Warm Keys", category: "Keys", genres: ["R&B", "Soul", "Gospel"], moodMatch: ["Relaxed", "Romantic", "Hopeful"], energyMatch: ["Low", "Medium"] },
  { name: "Bell Pluck", category: "Bell", genres: ["Trap", "Afrobeats", "Phonk"], moodMatch: ["Dark", "Happy", "Mysterious"], energyMatch: ["Medium", "High"] },
  { name: "Analog Synth", category: "Synth", genres: ["Synthwave", "EDM", "Techno"], moodMatch: ["Dreamy", "Energetic"], energyMatch: ["Medium", "High"] },
  { name: "Wide Lead", category: "Lead", genres: ["EDM", "Future Bass", "Pop"], moodMatch: ["Epic", "Energetic"], energyMatch: ["High", "Extreme"] },
  { name: "Dark Pad", category: "Pad", genres: ["Trap", "Ambient", "Cinematic"], moodMatch: ["Dark", "Dreamy", "Mysterious"], energyMatch: ["Very Low", "Low", "Medium"] },
  { name: "Deep 808", category: "808", genres: ["Trap", "Drill", "Phonk"], moodMatch: ["Dark", "Aggressive"], energyMatch: ["Medium", "High"] },
  { name: "Sub Bass", category: "Bass", genres: ["House", "EDM", "Dubstep"], moodMatch: ["Energetic", "Aggressive"], energyMatch: ["High", "Extreme"] },
  { name: "Soft Strings", category: "Strings", genres: ["Classical", "Orchestral", "Cinematic"], moodMatch: ["Epic", "Sad", "Hopeful"], energyMatch: ["Low", "Medium", "High"] },
  { name: "Soft Choir", category: "Choir", genres: ["Gospel", "Cinematic", "Orchestral"], moodMatch: ["Epic", "Inspirational", "Mysterious"], energyMatch: ["Low", "Medium", "High"] },
  { name: "Warm Guitar", category: "Guitar", genres: ["Country", "Afrobeats", "Rock"], moodMatch: ["Relaxed", "Happy", "Confident"], energyMatch: ["Low", "Medium", "High"] },
  { name: "Soft Brass", category: "Brass", genres: ["Jazz", "Gospel", "Orchestral"], moodMatch: ["Epic", "Confident"], energyMatch: ["Medium", "High"] },
  { name: "Flute", category: "Woodwinds", genres: ["Classical", "Latin", "Cinematic"], moodMatch: ["Dreamy", "Hopeful"], energyMatch: ["Low", "Medium"] },
  { name: "Atmospheric FX", category: "FX", genres: ["Ambient", "Cinematic", "EDM"], moodMatch: ["Mysterious", "Dreamy"], energyMatch: ["Very Low", "Low", "High"] },
  { name: "Percussion Kit", category: "Percussion", genres: ["Afrobeats", "Latin", "House"], moodMatch: ["Energetic", "Happy"], energyMatch: ["Medium", "High"] },
];

export const PLUGINS: PluginRecommendationKnowledge[] = [
  { category: "Warm Piano", description: "Natural or felt piano category for emotional harmony and melodic parts.", instruments: ["Soft Piano", "Warm Keys"], genres: ["LoFi", "R&B", "Pop"], moods: ["Sad", "Romantic", "Hopeful"] },
  { category: "Bell Pluck", description: "Short bright bell or pluck category for trap, phonk, and afro melodic hooks.", instruments: ["Bell Pluck"], genres: ["Trap", "Afrobeats", "Phonk"], moods: ["Dark", "Happy", "Mysterious"] },
  { category: "Dark Pad", description: "Wide sustained pad category for atmosphere, tension, and musical glue.", instruments: ["Dark Pad", "Atmospheric FX"], genres: ["Trap", "Ambient", "Cinematic"], moods: ["Dark", "Dreamy", "Mysterious"] },
  { category: "Soft Choir", description: "Breathy choir or vocal pad category for cinematic and gospel color.", instruments: ["Soft Choir"], genres: ["Gospel", "Cinematic", "Orchestral"], moods: ["Epic", "Inspirational"] },
  { category: "Wide Lead", description: "Wide synth lead category for hooks, drops, and energetic top lines.", instruments: ["Wide Lead", "Analog Synth"], genres: ["EDM", "Future Bass", "Pop"], moods: ["Energetic", "Epic"] },
  { category: "Deep 808", description: "Sustained or sliding sub-bass category for low-end drive.", instruments: ["Deep 808", "Sub Bass"], genres: ["Trap", "Drill", "Phonk"], moods: ["Dark", "Aggressive"] },
  { category: "Warm Guitar", description: "Clean, nylon, or muted guitar category for organic rhythmic hooks.", instruments: ["Warm Guitar"], genres: ["Afrobeats", "Country", "Latin"], moods: ["Relaxed", "Happy"] },
  { category: "Soft Brass", description: "Brass ensemble category for confident accents and cinematic lifts.", instruments: ["Soft Brass"], genres: ["Jazz", "Gospel", "Orchestral"], moods: ["Epic", "Confident"] },
];

export const SONG_STRUCTURES: SongStructureKnowledge[] = [
  { name: "Loop", genres: ["Trap", "LoFi", "Phonk"], sections: [{ name: "Loop", bars: 8 }] },
  { name: "Trap Hook/Verse", genres: ["Trap", "Drill"], sections: [{ name: "Intro", bars: 4 }, { name: "Hook", bars: 8 }, { name: "Verse", bars: 16 }, { name: "Hook", bars: 8 }, { name: "Outro", bars: 4 }] },
  { name: "Verse/Hook", genres: ["Hip Hop", "Afrobeats", "Dancehall"], sections: [{ name: "Intro", bars: 4 }, { name: "Verse", bars: 16 }, { name: "Hook", bars: 8 }, { name: "Verse", bars: 16 }, { name: "Hook", bars: 8 }, { name: "Outro", bars: 4 }] },
  { name: "Verse/Chorus/Bridge", genres: ["Pop", "R&B", "Soul", "Country", "Gospel"], sections: [{ name: "Intro", bars: 4 }, { name: "Verse", bars: 16 }, { name: "Chorus", bars: 8 }, { name: "Verse", bars: 16 }, { name: "Bridge", bars: 8 }, { name: "Chorus", bars: 8 }, { name: "Outro", bars: 4 }] },
  { name: "Club Arrangement", genres: ["House", "Tech House", "Techno"], sections: [{ name: "Intro", bars: 16 }, { name: "Groove", bars: 16 }, { name: "Breakdown", bars: 16 }, { name: "Drop", bars: 32 }, { name: "Outro", bars: 16 }] },
  { name: "Build/Drop", genres: ["EDM", "Future Bass", "Dubstep"], sections: [{ name: "Intro", bars: 8 }, { name: "Build", bars: 16 }, { name: "Drop", bars: 16 }, { name: "Break", bars: 8 }, { name: "Drop", bars: 16 }] },
  { name: "Cinematic Cue", genres: ["Cinematic", "Orchestral", "Classical"], sections: [{ name: "Opening", bars: 8 }, { name: "Development", bars: 16 }, { name: "Climax", bars: 16 }, { name: "Resolution", bars: 8 }] },
  { name: "Evolving Texture", genres: ["Ambient"], sections: [{ name: "Fade In", bars: 16 }, { name: "Evolution", bars: 32 }, { name: "Release", bars: 16 }] },
];

export const TIME_SIGNATURES: TimeSignatureKnowledge[] = [
  { signature: [4, 4], description: "Common time for most popular, electronic, hip-hop, and dance styles.", genreRecommendations: GENRES.map((genre) => genre.name) },
  { signature: [3, 4], description: "Triple meter for waltz-like classical, cinematic, and ballad writing.", genreRecommendations: ["Classical", "Orchestral", "Cinematic", "Country"] },
  { signature: [6, 8], description: "Compound meter for soulful ballads, gospel, cinematic, and Afro-Latin feels.", genreRecommendations: ["Gospel", "Soul", "Latin", "Cinematic"] },
  { signature: [7, 8], description: "Asymmetrical meter for advanced progressive and cinematic patterns.", genreRecommendations: ["Cinematic", "Classical", "Rock"] },
  { signature: [5, 4], description: "Odd meter for jazz, progressive rock, and advanced scoring.", genreRecommendations: ["Jazz", "Rock", "Cinematic"] },
];
